import { useMemo, useState } from 'react';

const participants=[{name:'Alex Morgan',role:'Host · simulated',state:'synthetic',initials:'AM'},{name:'Research Room',role:'Observer',state:'monitoring',initials:'RR'},{name:'BTC Ledger Bot',role:'Synthetic data',state:'analysis',initials:'BL'}];
const events=[['21:57:08','STREAM','Playback loop started','info'],['21:57:14','CALL','Synthetic participant joined','success'],['21:57:22','BTC','Demo transaction parsed','warning'],['21:57:31','MEDIA','Frame marker inserted','info']];

export default function Home(){
 const[playing,setPlaying]=useState(true),[tab,setTab]=useState<'call'|'stream'>('call'),[scenario,setScenario]=useState('Synthetic investor call'),[eventsShown,setEventsShown]=useState(events);
 const progress=useMemo(()=>playing?67:42,[playing]);
 const addEvent=(kind:string,text:string,level:string)=>setEventsShown(e=>[[new Date().toLocaleTimeString([],{hour12:false}),kind,text,level],...e].slice(0,8));
 return <main className="app">
  <header className="topbar"><div className="brand"><span className="brandMark">LS</span><div><strong>LiveSim Lab</strong><small>MEDIA SIMULATION CONSOLE</small></div></div><div className="safety"><span className="dot"/> SIMULATION MODE <span className="sep">·</span> NO REAL IDENTITIES</div><button className="ghost" onClick={()=>addEvent('SYSTEM','Audit marker added','info')}>+ Audit marker</button></header>
  <section className="hero"><div><p className="eyebrow">SAFE MEDIA RESEARCH / 01</p><h1>Study the mechanics of a <em>convincing call.</em></h1><p className="lede">A controlled environment for understanding simulated livestreams, video calls, playback cues and synthetic Bitcoin activity—without impersonating real people, platforms or wallets.</p></div><div className="scenarioBox"><label>SCENARIO</label><select value={scenario} onChange={e=>setScenario(e.target.value)}><option>Synthetic investor call</option><option>Pre-recorded livestream</option><option>Video-call social engineering</option><option>Bitcoin transaction walkthrough</option></select><span>All identities and transactions are synthetic.</span></div></section>
  <section className="workspace"><div className="panel media"><div className="panelHead"><div className="tabs"><button className={tab==='call'?'active':''} onClick={()=>setTab('call')}>Video call</button><button className={tab==='stream'?'active':''} onClick={()=>setTab('stream')}>Livestream</button></div><span className="tag">PRE-RECORDED / SYNTHETIC</span></div><div className="stage"><div className="stageGrid"/><div className="fakeVideo"><div className="avatar">AM</div><div className="videoLabel"><b>Alex Morgan</b><span>AI-generated simulation · not a real person</span></div><div className="watermark">SIMULATED</div></div><div className="miniCall"><span className="miniAvatar">RR</span><span>Research Room</span><i>Observer</i></div><div className="mediaHud"><span>{playing?'00:14:28':'00:09:07'}</span><span>{progress}%</span></div></div><div className="controls"><button className="play" onClick={()=>setPlaying(!playing)}>{playing?'Ⅱ':'▶'}</button><div className="scrub"><span style={{width:progress+'%'}}/></div><span className="mono">{playing?'PLAYING':'PAUSED'}</span><button onClick={()=>addEvent('MEDIA',playing?'Playback paused':'Playback resumed','info')}>MARK</button></div></div>
  <aside className="panel participants"><div className="panelHead"><h2>Participants</h2><span className="count">03</span></div>{participants.map(p=><div className="participant" key={p.name}><span className="avatar small">{p.initials}</span><div><b>{p.name}</b><small>{p.role}</small></div><span className={'state '+p.state}>{p.state}</span></div>)}<div className="rule"/><div className="integrity"><span>◉</span><div><b>Integrity lock</b><small>No camera, microphone, wallet or identity data is captured.</small></div></div></aside></section>
  <section className="lower"><div className="panel ledger"><div className="panelHead"><div><p className="eyebrow">SYNTHETIC LEDGER</p><h2>Bitcoin activity</h2></div><span className="tag yellow">DEMO DATA</span></div><div className="tx"><div className="coin">₿</div><div><b>bc1q…7m2k</b><small>synthetic sender → synthetic receiver</small></div><strong>0.018420 BTC</strong></div><div className="txMeta"><span>TX DEMO-7F2A</span><span>6 confirmations (simulated)</span><span>Fee 0.000012 BTC</span></div><button className="outline" onClick={()=>addEvent('BTC','Synthetic transaction inspected','warning')}>Inspect synthetic transaction</button></div>
  <div className="panel logs"><div className="panelHead"><div><p className="eyebrow">EVENT LOG</p><h2>Timeline</h2></div><button className="ghost" onClick={()=>setEventsShown([])}>Clear</button></div><div className="eventList">{eventsShown.length?eventsShown.map((e,i)=><div className="event" key={i}><time>{e[0]}</time><span className={'eventDot '+e[3]}/><div><b>{e[1]}</b><span>{e[2]}</span></div></div>):<div className="empty">No events. Use the console controls to create audit markers.</div>}</div></div></section>
  <footer><span>LiveSim Lab · research console</span><span>SIMULATED MEDIA · SYNTHETIC BTC · NO REAL TRANSACTIONS</span></footer>
 </main>;
}
