import React,{useRef,useState} from 'react';
import {Camera,Check,ChevronDown,Download,Film,Gauge,Layers,Mic,Play,Radio,ShieldCheck,SlidersHorizontal,Upload,Video,Volume2,Wifi,X,Zap} from 'lucide-react';
import './deep-live-cam.css';

const WORKER=import.meta.env.VITE_DEEP_LIVE_WORKER_URL||'/api/deep-live';
const PROVIDERS=[['cpu','CPU'],['cuda','NVIDIA CUDA'],['directml','Windows DirectML'],['coreml','Apple CoreML'],['openvino','Intel OpenVINO']];
const DEFAULTS={enhance:true,manyFaces:false,mouthMask:false,keepFps:true,keepAudio:true,keepFrames:false,encoder:'libx264',quality:23,provider:'cpu'};

export default function DeepLiveCamLab(){
 const sourceRef=useRef(),targetRef=useRef(),cameraRef=useRef();
 const [source,setSource]=useState(null),[target,setTarget]=useState(null),[live,setLive]=useState(false),[busy,setBusy]=useState(false),[settings,setSettings]=useState(DEFAULTS),[result,setResult]=useState(null),[error,setError]=useState(''),[worker,setWorker]=useState('unknown');
 const patch=(p)=>setSettings(s=>({...s,...p}));
 const file=(setter)=>e=>{const f=e.target.files?.[0];if(f)setter({name:f.name,url:URL.createObjectURL(f),file:f})};
 const probe=async()=>{try{const r=await fetch(`${WORKER}/health`);setWorker(r.ok?'online':'offline')}catch{setWorker('offline')}};
 React.useEffect(()=>{probe()},[]);
 const process=async()=>{setError('');setResult(null);if(!source||!target){setError('Choose a source face and target media first.');return}setBusy(true);try{const fd=new FormData();fd.append('source',source.file);fd.append('target',target.file);Object.entries(settings).forEach(([k,v])=>fd.append(k,String(v)));const r=await fetch(`${WORKER}/process`,{method:'POST',body:fd});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.error||'Deep Live Cam worker is not connected.');setResult({...d,url:d.url?.startsWith('http')?d.url:`${WORKER}${d.url}`})}catch(e){setError(e.message)}finally{setBusy(false)}};
 const toggleLive=async()=>{if(live){setLive(false);cameraRef.current?.srcObject?.getTracks().forEach(t=>t.stop());cameraRef.current.srcObject=null;return}try{const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});cameraRef.current.srcObject=s;setLive(true)}catch(e){setError(e?.name==='NotAllowedError'?'Camera permission was denied.':'Camera could not be started.')} };
 return <section className="dlcLab">
  <div className="dlcHead"><div><span className="dlcKicker">DEEP-LIVE CAM INTEGRATION</span><h2>Live face & media processor</h2><p>Imported as a dedicated processing workspace. The browser handles media selection and preview; GPU inference runs only through an explicitly configured Deep-Live-Cam worker.</p></div><div className={`worker ${worker}`}><i/>{worker==='online'?'ENGINE CONNECTED':worker==='offline'?'ENGINE OFFLINE':'CHECKING ENGINE'}</div></div>
  <div className="dlcNotice"><ShieldCheck size={17}/><span>Use only faces and media you have permission to process. Outputs are marked as synthetic media in the LiveSim Lab workflow.</span></div>
  <div className="dlcGrid">
   <div className="dlcCard inputs"><div className="dlcCardTop"><b>01 / SOURCE FACE</b><button onClick={()=>sourceRef.current?.click()}><Upload size={14}/> Choose</button></div><input ref={sourceRef} type="file" accept="image/*" hidden onChange={file(setSource)}/><div className="asset">{source?<><img src={source.url}/><div><b>{source.name}</b><small>Source face selected</small></div><button onClick={()=>setSource(null)}><X size={14}/></button></>:<button className="empty" onClick={()=>sourceRef.current?.click()}><Camera size={22}/><span>Upload a source face</span><small>PNG / JPG / WEBP</small></button>}</div></div>
   <div className="dlcCard inputs"><div className="dlcCardTop"><b>02 / TARGET MEDIA</b><button onClick={()=>targetRef.current?.click()}><Upload size={14}/> Choose</button></div><input ref={targetRef} type="file" accept="video/*,image/*" hidden onChange={file(setTarget)}/><div className="asset">{target?<><video src={target.url} muted playsInline/><div><b>{target.name}</b><small>Target media selected</small></div><button onClick={()=>setTarget(null)}><X size={14}/></button></>:<button className="empty" onClick={()=>targetRef.current?.click()}><Film size={22}/><span>Upload target image or video</span><small>MP4 / MOV / WEBM / image</small></button>}</div></div>
   <div className="dlcCard preview"><div className="dlcCardTop"><b>03 / LIVE CAMERA</b><button className={live?'liveOn':''} onClick={toggleLive}>{live?<><Radio size={14}/> Stop live</>:<><Video size={14}/> Start live</>}</button></div><div className="camera"><video ref={cameraRef} autoPlay muted playsInline/><div className="cameraOverlay"><span>{live?'CAMERA ACTIVE':'CAMERA PREVIEW'}</span><i/></div>{!live&&<div className="cameraEmpty"><Camera size={26}/><span>Camera preview</span><small>Permission is requested only after Start live.</small></div>}</div></div>
  </div>
  <div className="dlcWorkspace">
   <div className="dlcCard options"><div className="dlcCardTop"><div><b>PROCESSING PIPELINE</b><small>Controls map directly to Deep-Live-Cam concepts.</small></div><SlidersHorizontal size={17}/></div>
    <div className="toggles">{[['enhance','Face enhancement','GFPGAN post-processing'],['manyFaces','Many faces','Process every detected face'],['mouthMask','Mouth mask','Preserve source mouth movement'],['keepFps','Keep FPS','Preserve target frame rate'],['keepAudio','Keep audio','Retain target audio track'],['keepFrames','Keep frames','Retain intermediate frames']].map(([k,n,d])=><button key={k} className={settings[k]?'active':''} onClick={()=>patch({[k]:!settings[k]})}><span>{settings[k]?<Check size={13}/>:''}</span><div><b>{n}</b><small>{d}</small></div></button>)}</div>
    <label className="select"><span>Execution provider</span><select value={settings.provider} onChange={e=>patch({provider:e.target.value})}>{PROVIDERS.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select><ChevronDown size={14}/></label>
    <div className="two"><label className="select"><span>Video encoder</span><select value={settings.encoder} onChange={e=>patch({encoder:e.target.value})}><option value="libx264">libx264</option><option value="libx265">libx265</option><option value="libvpx-vp9">libvpx-vp9</option></select><ChevronDown size={14}/></label><label className="range"><span>Quality <b>{settings.quality}</b></span><input type="range" min="0" max="51" value={settings.quality} onChange={e=>patch({quality:Number(e.target.value)})}/><small>0 lossless · 51 lowest</small></label></div>
    <button className="process" disabled={busy||worker!=='online'} onClick={process}>{busy?<><Gauge className="spin" size={16}/> Processing media…</>:<><Zap size={16}/> Run Deep-Live-Cam</>}</button>{worker!=='online'&&<small className="offline">Connect the GPU worker to enable inference. No simulated result is returned.</small>}{error&&<div className="err">{error}</div>}
   </div>
   <div className="dlcCard result"><div className="dlcCardTop"><div><b>OUTPUT</b><small>Processed media appears here when the worker returns a real artifact.</small></div><Download size={17}/></div>{result?.url?<><video src={result.url} controls playsInline/><a className="download" href={result.url} download><Download size={14}/> Download output</a></>:<div className="resultEmpty"><Layers size={28}/><b>No processed output</b><span>Run the configured engine to populate this panel.</span></div>}</div>
  </div>
 </section>
}
