import React,{useEffect,useRef,useState} from 'react';
import {getStored} from './lib/storage.js';
import WorkerConsole from './WorkerConsole.jsx';
import SetupAssistant from './SetupAssistant.jsx';
import './setup-assistant.css';
import {FaceDetector,ImageSegmenter,FilesetResolver} from '@mediapipe/tasks-vision';
import {Camera,CameraOff,CircleDot,Mic,MicOff,MonitorUp,Phone,Radio,Save,ShieldCheck,SlidersHorizontal,Square,Upload,Video,Volume2,Wifi,WifiOff,X,Zap,Image as ImageIcon,Play,Pause,RefreshCw,ExternalLink,FolderOpen,Film,Layers3} from 'lucide-react';

const PIPELINE=[['source','Camera / File Source'],['detect','Face Detector'],['mark','Face Marker'],['swap','Face Swapper / Animator'],['merge','Face Merger'],['output','Stream Output']];
const PLATFORMS=[['whatsapp','WhatsApp'],['google','Google Meet'],['zoom','Zoom'],['telegram','Telegram'],['tiktok','TikTok LIVE'],['rtmp','Custom RTMP'],['webrtc','WebRTC peer']];

function AvatarStudio({onReady,outputCanvasRef}){
 const [target,setTarget]=useState(null),[background,setBackground]=useState(null),[backgroundMode,setBackgroundMode]=useState('original'),[driver,setDriver]=useState(false),[tracking,setTracking]=useState(false),[renderer,setRenderer]=useState('proxy'),[calibrated,setCalibrated]=useState(false),[status,setStatus]=useState('idle'),[fps,setFps]=useState(0),[face,setFace]=useState({x:0,y:0,scale:1,rotation:0,mouth:0}),[gpuSession,setGpuSession]=useState(null),[gpuState,setGpuState]=useState('offline'),[aiOutput,setAiOutput]=useState(false),[streamReady,setStreamReady]=useState(false),[segmentation,setSegmentation]=useState(false);
 const cam=useRef(null),track=useRef(null),raf=useRef(null),last=useRef(performance.now()),frames=useRef(0),targetUrl=useRef(null),backgroundUrl=useRef(null),detector=useRef(null),segmenter=useRef(null),outputStream=useRef(null),targetImage=useRef(null),backgroundImage=useRef(null),driverCanvas=useRef(null),gpuBusy=useRef(false);
 const worker=import.meta.env.VITE_DEEP_LIVE_WORKER_URL||'';const gpuWorker=import.meta.env.VITE_LIVESIM_GPU_WORKER_URL||worker;const gpuSocket=useRef(null);
 useEffect(()=>()=>{stopDriver();if(targetUrl.current)URL.revokeObjectURL(targetUrl.current);if(backgroundUrl.current)URL.revokeObjectURL(backgroundUrl.current)},[]);
 useEffect(()=>{if(!target||!outputCanvasRef.current)return;const canvas=outputCanvasRef.current;canvas.width=1280;canvas.height=720;if(!outputStream.current&&canvas.captureStream)outputStream.current=canvas.captureStream(30);setStreamReady(Boolean(outputStream.current))},[target]);
 useEffect(()=>{if(target&&outputStream.current&&streamReady)onReady?.({...target,stream:outputStream.current})},[target,streamReady]);
 useEffect(()=>{if(driver&&gpuSession&&renderer==='gpu'&&target&&gpuSocket.current?.readyState!==1)connectGpuDriver()},[driver,gpuSession,renderer,target]);
 const loadBackground=e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return setStatus('Choose a background image');if(backgroundUrl.current)URL.revokeObjectURL(backgroundUrl.current);backgroundUrl.current=URL.createObjectURL(f);const image=new Image();image.onload=()=>{backgroundImage.current=image};image.src=backgroundUrl.current;setBackground({name:f.name,url:backgroundUrl.current,file:f});setBackgroundMode('image');setStatus('background-ready');};
 const loadTarget=e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return setStatus('Choose a portrait image');if(targetUrl.current)URL.revokeObjectURL(targetUrl.current);targetUrl.current=URL.createObjectURL(f);const image=new Image();image.onload=()=>{targetImage.current=image};image.src=targetUrl.current;const v={name:f.name,url:targetUrl.current,file:f};setTarget(v);setStatus('target-ready');if(gpuSession)uploadTargetToGpu(gpuSession,f).catch(e=>setStatus(e.message));onReady?.({...v,stream:null});};
 const startDriver=async()=>{if(driver){stopDriver();return}try{await initDetector();const s=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:false});track.current=s;cam.current.srcObject=s;setDriver(true);setTracking(Boolean(detector.current));setStatus(detector.current?'tracking':'tracker-unavailable');setSegmentation(Boolean(segmenter.current));if(detector.current){if(gpuSession)connectGpuDriver();loop()}}catch(e){setStatus(e?.name==='NotAllowedError'?'Camera permission denied':'Camera unavailable')}};
 const stopDriver=()=>{track.current?.getTracks().forEach(t=>t.stop());track.current=null;if(cam.current)cam.current.srcObject=null;detector.current?.close?.();detector.current=null;segmenter.current?.close?.();segmenter.current=null;gpuSocket.current?.close?.();gpuSocket.current=null;setDriver(false);setTracking(false);if(raf.current)cancelAnimationFrame(raf.current);setFps(0)};
 const connectGpuDriver=(sessionId=gpuSession)=>{if(!sessionId||!gpuWorker||!target)return;const u=gpuWorker.replace(/^http/,'ws').replace(/\/$/,'')+'/sessions/'+sessionId+'/driver';const ws=new WebSocket(u);ws.binaryType='blob';gpuSocket.current=ws;ws.onopen=()=>setGpuState('streaming');ws.onmessage=e=>{if(typeof e.data==='string')return;const url=URL.createObjectURL(e.data);const img=new Image();img.onload=()=>{const canvas=outputCanvasRef.current;if(canvas){const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,canvas.width,canvas.height)}URL.revokeObjectURL(url)};img.src=url};ws.onclose=()=>setGpuState('ready');ws.onerror=()=>setGpuState('error');};
 const initDetector=async()=>{try{const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm');segmenter.current=await ImageSegmenter.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/image_segmenter/selfie_segmenter_landscape/float16/latest/selfie_segmenter_landscape.tflite',delegate:'GPU'},runningMode:'VIDEO',outputCategoryMask:false,outputConfidenceMasks:true});detector.current=await FaceDetector.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite',delegate:'GPU'},runningMode:'VIDEO',minDetectionConfidence:.55});setStatus('tracking-ready')}catch(e){detector.current=null;setStatus('Face tracker unavailable') }};
 const loop=()=>{const now=performance.now();frames.current++;if(now-last.current>1000){setFps(frames.current);frames.current=0;last.current=now}const v=cam.current;if(v?.videoWidth&&detector.current&&v.readyState>=2){try{const result=detector.current.detectForVideo(v,now);const d=result.detections?.[0];if(d){const b=d.boundingBox,k=d.keypoints||[];const cx=b.originX+b.width/2,cy=b.originY+b.height/2;const nx=Math.max(-14,Math.min(14,(cx/v.videoWidth-.5)*34)),ny=Math.max(-10,Math.min(10,(cy/v.videoHeight-.5)*24));const scale=Math.max(.82,Math.min(1.18,1+((b.width/v.videoWidth)-.35)*.9));let rotation=0;if(k.length>=2){const a=k[0],bb=k[1];rotation=Math.max(-18,Math.min(18,Math.atan2(bb.y-a.y,bb.x-a.x)*180/Math.PI))}const next={x:nx,y:ny,scale,rotation,mouth:0};setFace(next);setTracking(true);drawOutput(next)}else setTracking(false)}catch{}}raf.current=requestAnimationFrame(loop)};
 const drawBackground=(ctx,w,h)=>{if(backgroundMode==='original'){ctx.drawImage(cam.current,0,0,w,h);return}if(backgroundMode==='blur'){ctx.save();ctx.filter='blur(22px)';ctx.drawImage(cam.current,-20,-20,w+40,h+40);ctx.restore();return}const bg=backgroundMode==='target'?targetImage.current:backgroundImage.current;if(bg?.complete){const s=Math.max(w/bg.naturalWidth,h/bg.naturalHeight),bw=bg.naturalWidth*s,bh=bg.naturalHeight*s;ctx.drawImage(bg,(w-bw)/2,(h-bh)/2,bw,bh)}else ctx.fillStyle='#10151d',ctx.fillRect(0,0,w,h)};
 const compositeDriver=async()=>{const v=cam.current,d=driverCanvas.current||(driverCanvas.current=document.createElement('canvas'));if(!v?.videoWidth||!v?.videoHeight)return;d.width=640;d.height=360;const dc=d.getContext('2d');if(backgroundMode==='original'){dc.drawImage(v,0,0,d.width,d.height);return d}if(!segmenter.current){dc.drawImage(v,0,0,d.width,d.height);return d}try{const result=segmenter.current.segmentForVideo(v,performance.now());const mask=result?.confidenceMasks?.[0]?.getAsFloat32Array();if(!mask){dc.drawImage(v,0,0,d.width,d.height);return d}const src=document.createElement('canvas');src.width=d.width;src.height=d.height;src.getContext('2d').drawImage(v,0,0,d.width,d.height);drawBackground(dc,d.width,d.height);const fg=src.getContext('2d').getImageData(0,0,d.width,d.height),out=dc.getImageData(0,0,d.width,d.height),mw=Math.sqrt(mask.length),mh=mw;for(let y=0;y<d.height;y++){for(let x=0;x<d.width;x++){const mi=Math.min(mask.length-1,Math.floor(y/d.height*mh)*mw+Math.floor(x/d.width*mw));const a=Math.max(0,Math.min(1,mask[mi]||0));const i=(y*d.width+x)*4;out.data[i]=fg.data[i]*a+out.data[i]*(1-a);out.data[i+1]=fg.data[i+1]*a+out.data[i+1]*(1-a);out.data[i+2]=fg.data[i+2]*a+out.data[i+2]*(1-a);out.data[i+3]=255}}dc.putImageData(out,0,0);result.confidenceMasks?.[0]?.close?.();return d}catch{dc.drawImage(v,0,0,d.width,d.height);return d}};
 const drawOutput=async(f)=>{const canvas=outputCanvasRef.current,img=targetImage.current;if(!canvas||!img?.complete)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);if(backgroundMode==='original'){ctx.fillStyle='#070a0f';ctx.fillRect(0,0,canvas.width,canvas.height)}else{if(backgroundMode==='blur'){ctx.save();ctx.filter='blur(24px)';ctx.drawImage(cam.current,-24,-24,canvas.width+48,canvas.height+48);ctx.restore()}else{const bg=backgroundMode==='target'?targetImage.current:backgroundImage.current;if(bg?.complete){const s=Math.max(canvas.width/bg.naturalWidth,canvas.height/bg.naturalHeight),bw=bg.naturalWidth*s,bh=bg.naturalHeight*s;ctx.drawImage(bg,(canvas.width-bw)/2,(canvas.height-bh)/2,bw,bh)}}}const scale=Math.min(canvas.width/img.naturalWidth,canvas.height/img.naturalHeight)*.82;const w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.save();ctx.translate(canvas.width/2+f.x*12,canvas.height/2+f.y*8);ctx.rotate(f.rotation*Math.PI/180);ctx.scale(f.scale,f.scale);ctx.drawImage(img,-w/2,-h/2,w,h);ctx.restore();if(renderer==='gpu'&&gpuSocket.current?.readyState===1&&!gpuBusy.current){const d=await compositeDriver();if(!d)return;gpuBusy.current=true;d.toBlob(blob=>{if(blob&&gpuSocket.current?.readyState===1)gpuSocket.current.send(blob);gpuBusy.current=false},'image/jpeg',.78)}};
 const calibrate=()=>{if(!driver)return setStatus('Start the motion driver first');setCalibrated(true);setStatus('calibrated')};
 const uploadTargetToGpu=async(sessionId,targetFile)=>{if(!gpuWorker||!sessionId||!targetFile)return false;const fd=new FormData();fd.append('source',targetFile);const r=await fetch(gpuWorker.replace(/\/$/,'')+'/sessions/'+sessionId+'/source',{method:'POST',body:fd});if(!r.ok)throw new Error(await r.text());return true};
 const useGpu=async()=>{if(!gpuWorker)return setStatus('GPU worker URL is not configured');try{const r=await fetch(gpuWorker.replace(/\/$/,'')+'/sessions',{method:'POST'});if(!r.ok)throw new Error('GPU worker rejected the session');const data=await r.json();if(data.status!=='ready')throw new Error(data.error||'GPU renderer failed to initialize');setGpuSession(data.sessionId);setGpuState('ready');setRenderer('gpu');if(target?.file)await uploadTargetToGpu(data.sessionId,target.file);setStatus('gpu-ready');return data.sessionId}catch(e){setGpuState('offline');setStatus(e.message||'GPU worker unavailable');return null}};
 const startAiOutput=async()=>{if(aiOutput){stopAiOutput();return}if(!target)return setStatus('Upload an authorized portrait before starting AI output');setStatus('starting-ai-output');setAiOutput(false);try{if(!driver)await startDriver();const sessionId=await useGpu();if(!sessionId)throw new Error('GPU renderer could not start');connectGpuDriver(sessionId);setAiOutput(true);setStatus('ai-output-starting');onReady?.({...target,active:true,renderer:'gpu',stream:outputStream.current});}catch(e){setAiOutput(false);setStatus(e.message||'Unable to start AI output')}};
 const stopAiOutput=()=>{gpuSocket.current?.close?.();gpuSocket.current=null;setAiOutput(false);setGpuState(gpuSession?'ready':'offline');setStatus('ai-output-stopped');setRenderer('proxy')};
 return <section className="avatarStudio">
  <div className="avatarHeader"><div><span>AVATAR / FACE STUDIO</span><h3>Drive an uploaded face with your camera</h3><p>Your camera supplies motion. The selected portrait is the visible identity. The GPU renderer can replace the browser motion proxy when a configured worker is online.</p></div><div className="avatarStatus"><i className={aiOutput?'live':tracking?'live':''}/>{aiOutput?'AI OUTPUT LIVE':tracking?'FACE DRIVER LIVE':'DRIVER IDLE'}<small>{aiOutput?'GPU worker + camera pipeline':renderer==='gpu'?'GPU renderer':'Browser motion proxy'}</small></div></div>
  <div className="avatarGrid">
   <div className="avatarPreview"><div className="avatarCanvas">{target?<canvas ref={outputCanvas} className="avatarOutputCanvas" aria-label="Neural avatar output"/>:<div className="avatarEmpty"><ImageIcon size={30}/><b>Upload a portrait</b><small>The portrait becomes the visible face.</small></div>}<div className="avatarHud"><span>{tracking?'DRIVER TRACKING':'READY'}</span><span>{fps?fps+' FPS':'-- FPS'}</span></div></div><video ref={cam} muted autoPlay playsInline className="driverPreview"/><div className="avatarActions"><button onClick={()=>document.getElementById('avatar-target-input')?.click()}><Upload size={15}/> Upload face</button><button onClick={()=>document.getElementById('avatar-bg-input')?.click()}><ImageIcon size={15}/> Upload background</button><button className={driver?'on':''} onClick={startDriver}>{driver?<><CameraOff size={15}/> Stop driver</>:<><Camera size={15}/> Use my camera</>}</button><button onClick={calibrate} disabled={!driver}><RefreshCw size={15}/> Calibrate</button><input id="avatar-target-input" hidden type="file" accept="image/*" onChange={loadTarget}/><input id="avatar-bg-input" hidden type="file" accept="image/*" onChange={loadBackground}/></div></div>
   <aside className="avatarControls"><div><span>REAL BACKGROUND</span><div className="bgModes"><button className={backgroundMode==='original'?'selected':''} onClick={()=>setBackgroundMode('original')}>Original room</button><button className={backgroundMode==='blur'?'selected':''} onClick={()=>setBackgroundMode('blur')}>Natural blur</button><button className={backgroundMode==='image'?'selected':''} onClick={()=>setBackgroundMode('image')} disabled={!background}>Uploaded photo</button><button className={backgroundMode==='target'?'selected':''} onClick={()=>setBackgroundMode('target')} disabled={!target}>Use target photo</button></div><small>{segmentation?'Person segmentation ready':'Segmentation loads with the motion driver.'} Backgrounds are user-provided images or the real camera scene; no AI-generated backdrop is required.</small></div><div><span>RENDER MODE</span><button className={renderer==='proxy'?'selected':''} onClick={()=>setRenderer('proxy')}>Face tracking preview</button><button className={renderer==='gpu'?'selected':''} onClick={useGpu}>GPU face renderer</button><small>MediaPipe tracks your camera locally and segments the person when a custom background is selected. The GPU path is the production route for expression transfer, temporal stabilization and final rendered video.</small></div><div><span>DRIVER SIGNALS</span><label>Head position <b>{face.x.toFixed(1)}, {face.y.toFixed(1)}</b></label><label>Scale <b>{face.scale.toFixed(3)}×</b></label><label>Rotation <b>{face.rotation.toFixed(1)}°</b></label><label>Mouth activity <b>{Math.round(face.mouth*100)}%</b></label></div><div><span>SESSION HANDOFF</span><p>{target?'Target loaded: '+target.name:'No target image loaded.'}</p><button className="primary aiOutputButton" disabled={!target||(!driver&&aiOutput)} onClick={startAiOutput}>{aiOutput?<><Square size={14}/> Stop AI output</>:<><Zap size={14}/> Start AI output</>}</button><button disabled={!target||!driver} onClick={()=>onReady?.({...target,active:true,renderer,stream:outputStream.current})}><Play size={14}/> Use avatar in session</button></div></aside>
  </div>
 </section>
}

export default function LiveSessionEngine({outputCanvasRef,initialDestination=''}){
 const [mode,setMode]=useState('call'),[camera,setCamera]=useState(false),[screen,setScreen]=useState(false),[mic,setMic]=useState(false),[media,setMedia]=useState(null),[voice,setVoice]=useState(()=>getStored('livesim.voiceProfileId','')),[destination,setDestination]=useState(''),[connected,setConnected]=useState(false);
 const [callState,setCallState]=useState('idle'),[streamState,setStreamState]=useState('idle'),[worker,setWorker]=useState('checking'),[gateway,setGateway]=useState('checking');
 const [connection,setConnection]=useState(null),[connecting,setConnecting]=useState(false);
 const [destinationNotice,setDestinationNotice]=useState('');
 const [brightness,setBrightness]=useState(100),[contrast,setContrast]=useState(100),[saturation,setSaturation]=useState(100),[speed,setSpeed]=useState(1),[mirror,setMirror]=useState(false),[level,setLevel]=useState(0),[log,setLog]=useState([]);
 const [room,setRoom]=useState(''),[scene,setScene]=useState('call'),[platformSession,setPlatformSession]=useState(null),[platformBusy,setPlatformBusy]=useState(false),[savedScenes,setSavedScenes]=useState([]),[recording,setRecording]=useState(false),[avatar,setAvatar]=useState(null),[showAvatar,setShowAvatar]=useState(true);
 const cameraRef=useRef(null),fileRef=useRef(null),sceneRefs=useRef([]),streamRef=useRef(null),audioRef=useRef(null),raf=useRef(null),socket=useRef(null),pc=useRef(null),recorderRef=useRef(null),recordedRef=useRef([]);
 const env={worker:import.meta.env.VITE_LIVESIM_GPU_WORKER_URL||import.meta.env.VITE_DEEP_LIVE_WORKER_URL||'',signal:import.meta.env.VITE_LIVESIM_SIGNAL_URL||'',whip:import.meta.env.VITE_LIVESIM_WHIP_URL||'',gateway:import.meta.env.VITE_LIVESIM_MEDIA_GATEWAY_URL||'http://127.0.0.1:8788'};
 useEffect(()=>{if(initialDestination&&initialDestination!==destination){setDestination(initialDestination);setConnected(false);setConnection(null);setDestinationNotice('Destination selected: '+initialDestination+'. Only this destination will be used for the next session.')}},[initialDestination]);
 const addLog=(text,type='info')=>setLog(x=>[{time:new Date().toLocaleTimeString([],{hour12:false}),text,type},...x].slice(0,10));
 const sourceReady=Boolean(camera||screen||media||avatar);
 const refreshChecks=()=>{setWorker('checking');setGateway('checking');addLog('Running setup checks…','info');window.setTimeout(()=>{const w=env.worker?fetch(env.worker.replace(/\/$/,'')+'/health').then(r=>r.ok).catch(()=>false):Promise.resolve(false);const g=env.gateway?fetch(env.gateway.replace(/\/$/,'')+'/health').then(r=>r.ok).catch(()=>false):Promise.resolve(false);Promise.all([w,g]).then(([okWorker,okGateway])=>{setWorker(okWorker?'online':'offline');setGateway(okGateway?'online':'offline');addLog('Setup checks refreshed','success')})},0)};
 const runPreflight=()=>{const checks=[camera,obsReadyRef.current,worker==='online',Boolean(voice),Boolean(destination)];const first=checks.findIndex(x=>!x);if(first<0){addLog('Preflight passed: all five setup checks are ready','success');return true}const labels=['Camera','OBS','GPU worker','Authorized voice','Destination'];addLog('Preflight blocked at '+labels[first]+'. Fix that item in Setup Assistant.','error');return false};
 const obsReadyRef=useRef(false);

 useEffect(()=>{Promise.all([env.worker?fetch(env.worker.replace(/\/$/,'')+'/health').then(r=>r.ok):Promise.resolve(false),env.gateway?fetch(env.gateway.replace(/\/$/,'')+'/health').then(r=>r.ok):Promise.resolve(false),fetch('/api/connections').then(r=>r.ok?r.json():{connected:false}).catch(()=>({connected:false}))]).then(([w,g,c])=>{setWorker(w?'online':'offline');setGateway(g?'online':'offline');if(c?.connected){setConnection(c);setConnected(true)}}).catch(()=>{setWorker('offline');setGateway('offline')});const q=new URLSearchParams(window.location.search);const provider=q.get('connected');if(provider){fetch('/api/connections').then(r=>r.json()).then(c=>{if(c?.connected){setConnection(c);setConnected(true)};addLog((c?.label||provider)+' account connected','success')}).catch(()=>{});window.history.replaceState({},'',window.location.pathname+window.location.hash)}return()=>cleanup()},[]);
 const cleanup=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());if(raf.current)cancelAnimationFrame(raf.current);audioRef.current?.close?.().catch?.(()=>{});socket.current?.close?.();pc.current?.close?.()};
 const startCamera=async()=>{if(camera){streamRef.current?.getTracks().filter(t=>t.kind==='video').forEach(t=>t.stop());setCamera(false);addLog('Camera source stopped');return}try{const s=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:false});streamRef.current=s;cameraRef.current.srcObject=s;setCamera(true);addLog('Camera source connected','success')}catch(e){addLog(e?.name==='NotAllowedError'?'Camera permission denied':'Camera source unavailable','error')}};
 const startScreen=async()=>{if(screen){streamRef.current?.getTracks().filter(t=>t.kind==='video').forEach(t=>t.stop());setScreen(false);addLog('Screen capture stopped');return}try{const s=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:30}},audio:true});s.getVideoTracks()[0].onended=()=>{setScreen(false);addLog('Screen sharing ended')};streamRef.current=s;if(cameraRef.current)cameraRef.current.srcObject=s;setScreen(true);setCamera(false);addLog('Screen/window capture connected','success')}catch(e){addLog(e?.name==='NotAllowedError'?'Screen-share permission cancelled':'Screen capture unavailable','error')}};
 const startRecording=()=>{if(recording){recorderRef.current?.stop();setRecording(false);return}const s=streamRef.current;if(!s)return addLog('Start a source before recording','error');try{recordedRef.current=[];const r=new MediaRecorder(s);recorderRef.current=r;r.ondataavailable=e=>e.data.size&&recordedRef.current.push(e.data);r.onstop=()=>{const blob=new Blob(recordedRef.current,{type:r.mimeType||'video/webm'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='livesim-session.webm';a.click();addLog('Session recording saved locally','success')};r.start(1000);setRecording(true);addLog('Local session recording started','success')}catch(e){addLog('Browser recording unavailable','error')}};
 const moveScene=(index,delta)=>{const next=(index+delta+4)%4;sceneRefs.current[next]?.focus();};
 const saveScene=()=>{const snapshot={id:crypto.randomUUID(),name:scene,mode,brightness,contrast,saturation,speed,mirror,voice,destination,avatar:avatar?.name||null,background:background?.name||null,backgroundMode};setSavedScenes(x=>[snapshot,...x].slice(0,6));addLog('Scene saved locally','success')};
 const loadScene=s=>{setScene(s.name);setMode(s.mode);setBrightness(s.brightness);setContrast(s.contrast);setSaturation(s.saturation);setSpeed(s.speed);setMirror(s.mirror);setVoice(s.voice);setDestination(s.destination);addLog('Scene loaded: '+s.name,'success')};
 const startMic=async()=>{if(mic){streamRef.current?.getTracks().filter(t=>t.kind==='audio').forEach(t=>t.stop());setMic(false);setLevel(0);addLog('Microphone stopped');return}try{const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});if(!streamRef.current)streamRef.current=new MediaStream();s.getTracks().forEach(t=>streamRef.current.addTrack(t));const C=window.AudioContext||window.webkitAudioContext;if(C){const c=new C(),a=c.createAnalyser();a.fftSize=256;c.createMediaStreamSource(s).connect(a);audioRef.current=c;const d=new Uint8Array(a.frequencyBinCount);const draw=()=>{a.getByteFrequencyData(d);let sum=0;for(const n of d)sum+=n;setLevel(Math.min(1,(sum/d.length)/255*3));raf.current=requestAnimationFrame(draw)};draw()}setMic(true);addLog('Microphone connected','success')}catch(e){addLog(e?.name==='NotAllowedError'?'Microphone permission denied':'Microphone unavailable','error')}};
 const loadMedia=e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('video/'))return addLog('Choose a video file','error');setMedia({file:f,url:URL.createObjectURL(f)});addLog('File source loaded: '+f.name,'success')};
 const externalPlatformUrl=id=>({whatsapp:'https://web.whatsapp.com/',telegram:'https://web.telegram.org/'}[id]||null);
 const connectPlatform=()=>{if(!destination)return addLog('Choose a destination first','error');if(destination==='rtmp')return addLog('RTMP uses the configured media gateway; no fake login is shown');if(destination==='webrtc')return addLog('WebRTC peer uses the signaling gateway');const external=externalPlatformUrl(destination);if(external){window.open(external,'_blank','noopener,noreferrer');addLog('Opened '+(destination==='whatsapp'?'WhatsApp':'Telegram')+' in a new tab. These platforms use their own login/session rather than LiveSim OAuth.','success');return}setConnecting(true);window.location.assign('/api/oauth/start?provider='+encodeURIComponent(destination));};
 const selectPlatform=id=>{if((callState==='active'||streamState==='live')&&id!==destination){addLog('Stop the current session before switching destinations','error');return}setDestination(id);setConnected(false);setConnection(null);setDestinationNotice('Destination selected: '+id+'. Only this destination will receive the session.');if(id==='whatsapp'||id==='telegram'){const external=externalPlatformUrl(id);window.open(external,'_blank','noopener,noreferrer');addLog('Opened '+(id==='whatsapp'?'WhatsApp':'Telegram')+' for account/session access','success');}else if(id==='google'||id==='zoom'||id==='tiktok'){setConnecting(true);window.location.assign('/api/oauth/start?provider='+encodeURIComponent(id));}};

 const startPlatformSession=async()=>{if(!destination||destination==='rtmp'||destination==='webrtc')return addLog('Choose Google Meet, Zoom, TikTok or another supported destination first','error');if(!media&&!avatar&&!camera&&!screen)return addLog('Start a media source or avatar first','error');if(!voice)return addLog('Select an authorized voice profile','error');if(destination!=='whatsapp'&&destination!=='telegram'&&!connection)return addLog('Authorize the destination account first','error');setPlatformBusy(true);try{const r=await fetch('/api/session/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mediaName:avatar?.name||media?.name||'LiveSim media',voiceProfileId:voice,destination})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Platform session could not be started');setPlatformSession(data.platform);addLog(data.platform?.message||'Platform session created','success');const url=data.platform?.meetingUri||data.platform?.startUrl||data.platform?.joinUrl;if(url)window.open(url,'_blank','noopener,noreferrer');}catch(e){addLog(e.message||'Platform session failed','error')}finally{setPlatformBusy(false)}};
 const startCall=async()=>{if(callState==='active'){pc.current?.close();socket.current?.close();setCallState('idle');addLog('Call session ended');return}if(!camera&&!screen&&!media&&!avatar)return addLog('Start a source or activate an avatar','error');if(!voice)return addLog('Select an authorized voice profile','error');if(!connected&&destination&&destination!=='webrtc')return addLog('Connect the destination account first','error');if(!env.signal)return addLog('VITE_LIVESIM_SIGNAL_URL is not configured; call transport is not started','error');try{const s=streamRef.current||new MediaStream();const pcx=new RTCPeerConnection();pc.current=pcx;s.getTracks().forEach(t=>pcx.addTrack(t,s));pcx.onicecandidate=e=>{if(e.candidate)socket.current?.send(JSON.stringify({type:'candidate',candidate:e.candidate}))};const ws=new WebSocket(env.signal);socket.current=ws;ws.onopen=async()=>{const id=room||crypto.randomUUID().slice(0,8);setRoom(id);ws.send(JSON.stringify({type:'join',room:id,role:'publisher',destination,voiceProfileId:voice,avatar:avatar?.name||null}));const offer=await pcx.createOffer();await pcx.setLocalDescription(offer);ws.send(JSON.stringify({type:'offer',sdp:offer.sdp}))};ws.onmessage=async e=>{const m=JSON.parse(e.data);if(m.type==='answer')await pcx.setRemoteDescription({type:'answer',sdp:m.sdp});if(m.type==='candidate')await pcx.addIceCandidate(m.candidate)};ws.onerror=()=>addLog('Signaling gateway error','error');setCallState('active');addLog('Video call transport started','success')}catch(e){addLog(e.message||'Unable to start call','error')}};
 const startStream=async()=>{if(streamState==='live'){setStreamState('idle');addLog('Live stream stopped');return}if(!destination)return addLog('Select exactly one destination before starting the live stream','error');if(!camera&&!screen&&!media&&!avatar)return addLog('Start a source or activate an avatar','error');if(!voice)return addLog('Select an authorized voice profile','error');if(!env.whip)return addLog('VITE_LIVESIM_WHIP_URL is not configured; live publishing is not started','error');try{const s=streamRef.current;if(!s)return addLog('No media tracks available','error');const pcx=new RTCPeerConnection();pc.current=pcx;s.getTracks().forEach(t=>pcx.addTrack(t,s));const offer=await pcx.createOffer();await pcx.setLocalDescription(offer);const r=await fetch(env.whip,{method:'POST',headers:{'Content-Type':'application/sdp','X-LiveSim-Destination':destination},body:offer.sdp});if(!r.ok)throw new Error('Media gateway rejected the publish request');const answer=await r.text();await pcx.setRemoteDescription({type:'answer',sdp:answer});setStreamState('live');addLog('Live publish transport connected','success')}catch(e){addLog(e.message||'Live publish failed','error')}};
 const visual={filter:`brightness(${brightness}%) contrast(${contrast}%) saturate(${saturation}%)`,transform:`scaleX(${mirror?-1:1})`};
 return <section className="liveEngine">
  <div className="engineHero"><div><span className="engineKicker">LIVESIM SESSION ENGINE / REAL-TIME AVATAR PIPELINE</span><h2>Video call + live streaming control room</h2><p>Camera, screen or media source → face driver → authorized voice → processed output → call or stream transport.</p></div><div className="engineHealth"><span className={worker==='online'?'good':''}/><b>{worker==='online'?'PROCESSOR ONLINE':'PROCESSOR '+worker.toUpperCase()}</b><small>GPU media worker</small></div></div>
  {showAvatar&&<AvatarStudio onReady={a=>{setAvatar(a);if(a?.stream)streamRef.current=a.stream;addLog('Avatar target ready: '+a.name,'success')}}/>}
  <div className="sceneStrip"><div className="sceneTitle"><span>SCENES</span><small>Recall studio configurations</small></div>{['call','stream','screen','media'].map((x,index)=><button ref={el=>sceneRefs.current[index]=el} key={x} className={scene===x?'active':''} aria-pressed={scene===x} onClick={()=>{setScene(x);setMode(x==='stream'||x==='media'?'stream':'call')}} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowDown'){e.preventDefault();moveScene(index,1)}else if(e.key==='ArrowLeft'||e.key==='ArrowUp'){e.preventDefault();moveScene(index,-1)}else if(e.key==='Home'){e.preventDefault();sceneRefs.current[0]?.focus()}else if(e.key==='End'){e.preventDefault();sceneRefs.current[3]?.focus()}}}>{x==='call'?'Video Call':x==='stream'?'Live Stream':x==='screen'?'Screen Studio':'Media Playback'}</button>)}<button className="saveScene" onClick={saveScene}><Save size={14}/> Save</button></div>
  <div className="engineTabs"><button className={mode==='call'?'active':''} onClick={()=>setMode('call')}><Phone size={15}/> Video Call</button><button className={mode==='stream'?'active':''} onClick={()=>setMode('stream')}><Radio size={15}/> Live Stream</button><button className={mode==='pipeline'?'active':''} onClick={()=>setMode('pipeline')}><SlidersHorizontal size={15}/> Pipeline</button></div>
  <div className="studioCommandBar">
   <div className="projectIdentity"><span className="projectEyebrow">PROJECT / LIVESIM LAB</span><b>Realtime Session</b><small>Broadcast workspace · 1280 × 720</small></div>
   <div className="commandStatus"><span className="statusDot"/> ENGINE READY <i/> <span>{destination?('DESTINATION: '+destination.toUpperCase()):'NO DESTINATION'}</span></div>
   <div className="commandActions"><button onClick={()=>addLog('Session workspace checked','info')}><RefreshCw size={13}/> Check</button><button onClick={()=>setShowAvatar(v=>!v)}><ImageIcon size={13}/> Avatar</button></div>
  </div>
  <details className="studioGuide" open>
   <summary><span className="guideBadge">START HERE</span><b>LiveSim operating guide</b><small>Follow the green checks in order before starting a session.</small><span className="guideChevron">⌄</span></summary>
   <div className="guideBody">
    <div className="guideSteps">
     <article><strong>01</strong><b>Connect your camera</b><p>For a phone camera, open DroidCam first. For the most stable setup, connect by USB; Wi-Fi works when both devices share the same network.</p><em>CHECK · Camera source shows READY/LIVE</em></article>
     <article><strong>02</strong><b>Choose one source</b><p>Use Camera, Screen / Window, Media, or Avatar. Start with one source so you can see exactly what is entering the pipeline.</p><em>CHECK · Preview is moving</em></article>
     <article><strong>03</strong><b>Check processing</b><p>Watch the Processing Conveyor and Worker Console. A GPU worker marked Offline means the neural renderer is not available yet; do not treat the browser preview as neural output.</p><em>CHECK · Worker state is understood</em></article>
     <article><strong>04</strong><b>Configure output last</b><p>Select a destination only after your source and preview are correct. Do not press Start Live or Start Call while you are still testing the camera.</p><em>CHECK · Destination selected</em></article>
    </div>
    <div className="guideColumns">
     <div><span>PHONE → OBS QUICK PATH</span><b>DroidCam → OBS → LiveSim</b><ol><li>Open DroidCam on the phone.</li><li>In OBS add a DroidCam OBS source and refresh devices.</li><li>Select the phone and activate it.</li><li>Confirm the OBS preview is clean before using LiveSim output.</li></ol></div>
     <div><span>DO NOT SKIP</span><b>Preflight rules</b><ul><li>Use only faces, voices, media and accounts you are authorized to use.</li><li>Keep one camera source active while troubleshooting.</li><li>Do not enable audio in DroidCam unless you actually need it; video-only is recommended.</li><li>Keep the phone powered during long sessions.</li></ul></div>
     <div><span>IF SOMETHING IS RED</span><b>Fast diagnosis</b><ul><li><b>Camera offline:</b> check DroidCam/USB/Wi-Fi before touching LiveSim.</li><li><b>Worker offline:</b> browser tracking can still work, but neural rendering is unavailable.</li><li><b>Preview black:</b> stop the source, refresh it, then restart one source only.</li><li><b>Lag:</b> test 1280×720 at 30 FPS before increasing quality.</li></ul></div>
    </div>
    <div className="guideLegend"><span><i className="dot good"/>GREEN = ready/connected</span><span><i className="dot warn"/>AMBER = needs configuration</span><span><i className="dot bad"/>RED = stop and troubleshoot</span><span><i className="dot info"/>BLUE = information only</span></div>
   </div>
  </details>
  <SetupAssistant
   camera={camera}
   worker={worker}
   gateway={gateway}
   destination={destination}
   voice={voice}
   sourceReady={sourceReady}
   onStartCamera={startCamera}
   onWorkerHelp={()=>addLog('GPU worker offline. Start the configured LiveSim GPU worker on the workstation, then press Refresh checks.','error')}
   onDestination={()=>document.querySelector('.engineSide .platformGrid button')?.focus()}
   onVoice={()=>document.querySelector('.voiceLine input')?.focus()}
   onRefresh={refreshChecks}
   onPreflight={runPreflight}
   onObsStatus={ok=>{obsReadyRef.current=ok}}
  />
  <section className="studioAssetBin" aria-label="Project media browser">
   <div className="assetBinHead"><div><span>PROJECT BIN</span><b>Media & source assets</b><small>Local project assets stay in this browser session until you choose a transport.</small></div><div className="assetBinActions"><button onClick={()=>fileRef.current?.click()}><Upload size={12}/> Import video</button><button onClick={()=>document.getElementById('avatar-target-input')?.click()}><FolderOpen size={12}/> Add portrait</button></div></div>
   <div className="assetCards">
    <button className={'assetCard '+(camera?'selected':'')} onClick={startCamera}><span className="assetThumb camera"><Camera size={18}/></span><span><b>Camera source</b><small>{camera?'LIVE · 30 FPS':'Device camera'}</small></span><i>{camera?'LIVE':'READY'}</i></button>
    <button className={'assetCard '+(screen?'selected':'')} onClick={startScreen}><span className="assetThumb screen"><MonitorUp size={18}/></span><span><b>Screen / Window</b><small>{screen?'CAPTURING':'Desktop input'}</small></span><i>{screen?'LIVE':'READY'}</i></button>
    <button className={'assetCard '+(media?'selected':'')} onClick={()=>fileRef.current?.click()}><span className="assetThumb media"><Film size={18}/></span><span><b>{media?.name||'Media clip'}</b><small>{media?'Imported local video':'No clip imported'}</small></span><i>{media?'LOADED':'EMPTY'}</i></button>
    <button className={'assetCard '+(avatar?'selected':'')} onClick={()=>setShowAvatar(true)}><span className="assetThumb avatar"><ImageIcon size={18}/></span><span><b>{avatar?.name||'Portrait / avatar'}</b><small>{avatar?'Authorized target loaded':'Open Avatar Studio'}</small></span><i>{avatar?'READY':'OPEN'}</i></button>
    <div className="assetCard static"><span className="assetThumb pipeline"><Layers3 size={18}/></span><span><b>Processing graph</b><small>Source → tracker → renderer → output</small></span><i>LIVE</i></div>
   </div>
  </section>
  <div className="engineGrid">
   <aside className="sourceRail" aria-label="Studio sources">
    <div className="railSectionTitle"><span>SOURCES</span><small>INPUTS</small></div>
    <button className={camera?'sourceItem active':''} onClick={startCamera}><span className="sourceGlyph"><Camera size={15}/></span><span><b>Camera</b><small>{camera?'Live camera':'Local device'}</small></span><i>{camera?'ON':'+'}</i></button>
    <button className={screen?'sourceItem active':''} onClick={startScreen}><span className="sourceGlyph"><MonitorUp size={15}/></span><span><b>Screen / Window</b><small>{screen?'Capturing':'Desktop source'}</small></span><i>{screen?'ON':'+'}</i></button>
    <button className={media?'sourceItem active':''} onClick={()=>fileRef.current?.click()}><span className="sourceGlyph"><Video size={15}/></span><span><b>Media</b><small>{media?.name||'Video file'}</small></span><i>+</i></button>
    <button className={avatar?'sourceItem active':''} onClick={()=>setShowAvatar(v=>!v)}><span className="sourceGlyph"><ImageIcon size={15}/></span><span><b>Avatar</b><small>{avatar?.name||'Portrait driver'}</small></span><i>+</i></button>
    <div className="sourceDivider"/>
    <div className="railSectionTitle"><span>SCENES</span><small>SETS</small></div>
    {['call','stream','screen','media'].map(x=><button key={x} className={'sceneMini '+(scene===x?'active':'')} onClick={()=>{setScene(x);setMode(x==='stream'||x==='media'?'stream':'call')}}><span>{x==='call'?'VC':x==='stream'?'LIVE':x==='screen'?'DESK':'MEDIA'}</span><b>{x==='call'?'Video Call':x==='stream'?'Live Stream':x==='screen'?'Screen Studio':'Media Playback'}</b></button>)}
    <div className="sourceRailFooter"><ShieldCheck size={13}/><span>Authorized media only</span></div>
   </aside>
   <div className="engineStage"><div className="stageHead"><div><span>SOURCE / OUTPUT</span><b>{mode==='call'?'CALL PREVIEW':mode==='stream'?'LIVE PREVIEW':'PIPELINE PREVIEW'}</b></div><span className="liveBadge"><CircleDot size={11}/> {callState==='active'?'CALL LIVE':streamState==='live'?'STREAM LIVE':'READY'}</span></div><div className="engineVideo">{destinationNotice&&<div className="destinationNotice" role="status"><Radio size={12}/> {destinationNotice}</div>}{avatar?<div className="sessionAvatar"><img src={avatar.url} alt="Avatar output"/></div>:media&&!camera&&!screen?<video src={media.url} controls playsInline style={visual} onLoadedMetadata={e=>e.currentTarget.playbackRate=speed}/>:<video ref={cameraRef} autoPlay muted playsInline style={visual}/>}<div className="videoHud"><span>{avatar?'AVATAR OUTPUT':screen?'SCREEN / WINDOW':camera?'CAMERA':media?'FILE SOURCE':'NO SOURCE'}</span><span>{worker==='online'?'GPU READY':'WORKER OFFLINE'}</span></div>{!camera&&!screen&&!media&&!avatar&&<div className="emptyVideo"><Video size={28}/><b>Ready for a source</b><small>Start your camera, share a screen, load a video, or upload a portrait in Avatar Studio.</small><span>Nothing is sent anywhere until you select one destination and start the session.</span></div>}</div><div className="stageActions"><button onClick={startCamera} className={camera?'on':''}>{camera?<CameraOff size={15}/>:<Camera size={15}/>} {camera?'Stop camera':'Start camera'}</button><button onClick={startScreen} className={screen?'on':''}>{screen?<X size={15}/>:<MonitorUp size={15}/>} {screen?'Stop share':'Screen / Window'}</button><button onClick={()=>fileRef.current?.click()}><Upload size={15}/> Load video</button><button onClick={startRecording} className={recording?'on':''}>{recording?<Square size={14}/>:<CircleDot size={14}/>} {recording?'Stop rec':'Record'}</button><input ref={fileRef} hidden type="file" accept="video/*" onChange={loadMedia}/><button onClick={startMic} className={mic?'on':''}>{mic?<MicOff size={15}/>:<Mic size={15}/>} {mic?'Mute mic':'Mic'}</button><button onClick={()=>setShowAvatar(v=>!v)}><ImageIcon size={15}/> {showAvatar?'Hide avatar studio':'Avatar studio'}</button></div><div className="level"><span>MIC LEVEL</span><i><b style={{width:`${Math.max(2,level*100)}%`}}/></i></div></div>
   <aside className="engineSide"><div className="sideBlock"><span>DESTINATION</span><div className="platformGrid">{PLATFORMS.map(([id,name])=><button key={id} className={destination===id?'selected':''} onClick={()=>selectPlatform(id)} title={id==='rtmp'||id==='webrtc'?'Configure transport':'Open '+name+' connection'}>{name}{['whatsapp','telegram','google','zoom','tiktok'].includes(id)&&<ExternalLink size={11}/>}</button>)}</div>{destination&&destination!=='webrtc'&&destination!=='rtmp'&&<button className="connect" onClick={connectPlatform} disabled={connecting}><Wifi size={14}/> {connecting?'Opening…':connection?.provider===destination?'Connected — '+(connection.displayName||connection.label):'Open / connect account'}</button>}{destination&&['google','zoom','tiktok'].includes(destination)&&<button className="primary" onClick={startPlatformSession} disabled={platformBusy||(!connection)}><Play size={14}/> {platformBusy?'Starting…':destination==='tiktok'?'Verify creator / publish':'Create & open session'}</button>}{destination==='rtmp'&&<small className="sideNote">RTMP publishing requires a configured media gateway; browser code does not send RTMP directly.</small>}</div>
    <div className="sideBlock"><span>AUTHORIZED VOICE</span><div className="voiceLine"><Volume2 size={15}/><input value={voice} onChange={e=>setVoice(e.target.value)} placeholder="Voice profile ID"/></div><small className="sideNote">Use your own voice or a voice you have authorization to use.</small></div>
    <div className="sideBlock"><span>VIDEO CONTROL</span>{[['Brightness',brightness,setBrightness,50,150],['Contrast',contrast,setContrast,50,150],['Saturation',saturation,setSaturation,0,180],['Speed',speed,setSpeed,.5,2]].map(([n,v,set,min,max])=><label className="engineRange" key={n}><b>{n}</b><span>{n==='Speed'?v.toFixed(2)+'×':v+'%'}</span><input type="range" min={min} max={max} step={n==='Speed'?.05:1} value={v} onChange={e=>set(Number(e.target.value))}/></label>)}<button onClick={()=>setMirror(!mirror)} className={mirror?'selected':''}>Mirror {mirror?'on':'off'}</button></div>
   </aside>
  </div>

  <div className="timelineDock">
   <div className="timelineHead"><span>TIMELINE</span><small>LIVE SESSION / SCENE STACK</small><b>{recording?'RECORDING':'STANDBY'}</b></div>
   <div className="timelineTrack"><div className="timelineRuler"><span>00:00</span><span>00:15</span><span>00:30</span><span>00:45</span><span>01:00</span></div><div className="timelineLane"><i className="playhead"/><div className="timelineClip source"><b>INPUT</b><span>{camera?'Camera':screen?'Screen':media?.name||'No source'}</span></div><div className="timelineClip process"><b>PROCESS</b><span>{worker==='online'?'Neural pipeline':'Awaiting worker'}</span></div><div className="timelineClip output"><b>OUTPUT</b><span>{destination||'Select destination'}</span></div></div></div>
  </div>
  <div className="transportBar"><div><span>{mode==='call'?'CALL TRANSPORT':'STREAM TRANSPORT'}</span><b>{mode==='call'?callState.toUpperCase():streamState.toUpperCase()}</b></div><div className="transportInfo"><WifiOff size={14}/><span>Gateway: {gateway}</span><span>Worker: {worker}</span></div>{mode==='call'?<button className="primary" onClick={startCall}>{callState==='active'?<><Square size={14}/> End call</>:<><Phone size={14}/> Start video call</>}</button>:mode==='stream'?<button className="primary" onClick={startStream}>{streamState==='live'?<><Square size={14}/> Stop live</>:<><Radio size={14}/> Start live stream</>}</button>:<button className="primary" onClick={()=>addLog(worker==='online'?'Pipeline worker ready':'Connect the GPU worker before running inference',worker==='online'?'success':'error')}><Zap size={14}/> Run pipeline check</button>}</div>
  <div className="pipeline"><div className="pipelineHead"><div><span>PROCESSING CONVEYOR</span><b>Real-time face-driven output architecture</b></div><small>Camera → tracking → renderer → compositor → output</small></div><div className="pipelineNodes">{PIPELINE.map(([id,label],i)=><React.Fragment key={id}><div className={`node ${worker==='online'?'ready':''}`}><span>0{i+1}</span><b>{label}</b><small>{i===0?'Camera / file':i===1?'Detection':i===2?'Landmarks':i===3?'Face renderer':i===4?'Composite':i===5?'WebRTC / gateway':'Module'}</small></div>{i<PIPELINE.length-1&&<i className="pipe"/>}</React.Fragment>)}</div></div>
  <div id="worker-console"><WorkerConsole/></div>
  {savedScenes.length>0&&<div className="savedScenes"><span>SAVED SCENES</span>{savedScenes.map(s=><button key={s.id} onClick={()=>loadScene(s)}>{s.name}</button>)}</div>}<div className="engineLog"><div><span>SESSION LOG</span><b>Transport events</b></div>{log.length?log.map((x,i)=><div className={'logRow '+x.type} key={i}><code>{x.time}</code><span>{x.text}</span></div>):<div className="logEmpty">No session events yet.</div>}</div>
  <div className="engineFoot"><ShieldCheck size={15}/><span>Use only media, faces and accounts you are authorized to use. The MediaPipe tracking runs locally in the browser; the uploaded portrait is not claimed to be a neural face render until the GPU renderer is online.</span></div>
 </section>
}
