import React,{useEffect,useRef,useState} from 'react';
import {Camera,CameraOff,CircleDot,Film,Mic,MicOff,MonitorUp,Phone,Radio,Save,ShieldCheck,SlidersHorizontal,Square,Upload,Video,Volume2,Wifi,WifiOff,X,Zap} from 'lucide-react';

const PIPELINE=[['source','Camera / File Source'],['detect','Face Detector'],['mark','Face Marker'],['swap','Face Swapper / Animator'],['merge','Face Merger'],['output','Stream Output']];
const PLATFORMS=[['whatsapp','WhatsApp'],['google','Google Meet'],['zoom','Zoom'],['telegram','Telegram'],['tiktok','TikTok LIVE'],['rtmp','Custom RTMP'],['webrtc','WebRTC peer']];

export default function LiveSessionEngine(){
 const [mode,setMode]=useState('call');
 const [camera,setCamera]=useState(false),[mic,setMic]=useState(false),[media,setMedia]=useState(null),[voice,setVoice]=useState(''),[destination,setDestination]=useState(''),[connected,setConnected]=useState(false);
 const [callState,setCallState]=useState('idle'),[streamState,setStreamState]=useState('idle'),[worker,setWorker]=useState('checking'),[gateway,setGateway]=useState('checking');
 const [brightness,setBrightness]=useState(100),[contrast,setContrast]=useState(100),[saturation,setSaturation]=useState(100),[speed,setSpeed]=useState(1),[mirror,setMirror]=useState(false),[level,setLevel]=useState(0),[log,setLog]=useState([]);
 const [room,setRoom]=useState('');
 const cameraRef=useRef(null),fileRef=useRef(null),streamRef=useRef(null),audioRef=useRef(null),raf=useRef(null),socket=useRef(null),pc=useRef(null),recorderRef=useRef(null),recordedRef=useRef([]);
 const env={worker:import.meta.env.VITE_DEEP_LIVE_WORKER_URL||'',signal:import.meta.env.VITE_LIVESIM_SIGNAL_URL||'',whip:import.meta.env.VITE_LIVESIM_WHIP_URL||'',gateway:import.meta.env.VITE_LIVESIM_MEDIA_GATEWAY_URL||''};
 const addLog=(text,type='info')=>setLog(x=>[{time:new Date().toLocaleTimeString([],{hour12:false}),text,type},...x].slice(0,10));
 useEffect(()=>{Promise.all([env.worker?fetch(env.worker.replace(/\/$/,'')+'/health').then(r=>r.ok):Promise.resolve(false),env.gateway?fetch(env.gateway.replace(/\/$/,'')+'/health').then(r=>r.ok):Promise.resolve(false)]).then(([w,g])=>{setWorker(w?'online':'offline');setGateway(g?'online':'offline')}).catch(()=>{setWorker('offline');setGateway('offline')});return()=>cleanup()},[]);
 const cleanup=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());if(raf.current)cancelAnimationFrame(raf.current);audioRef.current?.close?.().catch?.(()=>{});socket.current?.close?.();pc.current?.close?.()};
 const startCamera=async()=>{if(camera){streamRef.current?.getTracks().filter(t=>t.kind==='video').forEach(t=>t.stop());setCamera(false);addLog('Camera source stopped');return}try{const s=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:false});const existing=streamRef.current;existing?.getTracks().filter(t=>t.kind==='video').forEach(t=>t.stop());streamRef.current=s;cameraRef.current.srcObject=s;setCamera(true);addLog('Camera source connected','success')}catch(e){addLog(e?.name==='NotAllowedError'?'Camera permission denied':'Camera source unavailable','error')}};
 const startScreen=async()=>{if(screen){streamRef.current?.getTracks().filter(t=>t.kind==='video').forEach(t=>t.stop());setScreen(false);addLog('Screen capture stopped');return}try{const s=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:30}},audio:true});s.getVideoTracks()[0].onended=()=>{setScreen(false);addLog('Screen sharing ended')};streamRef.current=s;if(cameraRef.current)cameraRef.current.srcObject=s;setScreen(true);setCamera(false);addLog('Screen/window capture connected','success')}catch(e){addLog(e?.name==='NotAllowedError'?'Screen-share permission cancelled':'Screen capture unavailable','error')}};
 const startRecording=()=>{if(recording){recorderRef.current?.stop();setRecording(false);return}const s=streamRef.current;if(!s)return addLog('Start a source before recording','error');try{recordedRef.current=[];const r=new MediaRecorder(s);recorderRef.current=r;r.ondataavailable=e=>e.data.size&&recordedRef.current.push(e.data);r.onstop=()=>{const blob=new Blob(recordedRef.current,{type:r.mimeType||'video/webm'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='livesim-session.webm';a.click();addLog('Session recording saved locally','success')};r.start(1000);setRecording(true);addLog('Local session recording started','success')}catch(e){addLog('Browser recording unavailable','error')}};
 const saveScene=()=>{const snapshot={id:crypto.randomUUID(),name:scene,mode,brightness,contrast,saturation,speed,mirror,voice,destination};setSavedScenes(x=>[snapshot,...x].slice(0,6));addLog('Scene saved locally','success')};
 const loadScene=s=>{setScene(s.name);setMode(s.mode);setBrightness(s.brightness);setContrast(s.contrast);setSaturation(s.saturation);setSpeed(s.speed);setMirror(s.mirror);setVoice(s.voice);setDestination(s.destination);addLog('Scene loaded: '+s.name,'success')};
 const startMic=async()=>{if(mic){streamRef.current?.getTracks().filter(t=>t.kind==='audio').forEach(t=>t.stop());setMic(false);setLevel(0);addLog('Microphone stopped');return}try{const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});if(!streamRef.current)streamRef.current=new MediaStream();s.getTracks().forEach(t=>streamRef.current.addTrack(t));const C=window.AudioContext||window.webkitAudioContext;if(C){const c=new C(),a=c.createAnalyser();a.fftSize=256;c.createMediaStreamSource(s).connect(a);audioRef.current=c;const d=new Uint8Array(a.frequencyBinCount);const draw=()=>{a.getByteFrequencyData(d);let sum=0;for(const n of d)sum+=n;setLevel(Math.min(1,(sum/d.length)/255*3));raf.current=requestAnimationFrame(draw)};draw()}setMic(true);addLog('Microphone connected','success')}catch(e){addLog(e?.name==='NotAllowedError'?'Microphone permission denied':'Microphone unavailable','error')}};
 const loadMedia=e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('video/'))return addLog('Choose a video file','error');setMedia({file:f,url:URL.createObjectURL(f)});addLog('File source loaded: '+f.name,'success')};
 const connectPlatform=()=>{if(!destination)return addLog('Choose a destination first','error');if(destination==='rtmp')return addLog('RTMP uses the configured media gateway; no fake login is shown');if(destination==='webrtc')return addLog('WebRTC peer uses the signaling gateway');window.location.href='/api/oauth/start?provider='+encodeURIComponent(destination)};
 const startCall=async()=>{if(callState==='active'){pc.current?.close();socket.current?.close();setCallState('idle');addLog('Call session ended');return}if(!camera&&!screen&&!media)return addLog('Start the camera, share your screen, or load a video source','error');if(!voice)return addLog('Select an authorized voice profile','error');if(!connected&&destination&&destination!=='webrtc')return addLog('Connect the destination account first','error');if(!env.signal)return addLog('VITE_LIVESIM_SIGNAL_URL is not configured; call transport is not started','error');try{const s=streamRef.current||new MediaStream();const pcx=new RTCPeerConnection();pc.current=pcx;s.getTracks().forEach(t=>pcx.addTrack(t,s));pcx.onicecandidate=e=>{if(e.candidate)socket.current?.send(JSON.stringify({type:'candidate',candidate:e.candidate}))};const ws=new WebSocket(env.signal);socket.current=ws;ws.onopen=async()=>{const id=room||crypto.randomUUID().slice(0,8);setRoom(id);ws.send(JSON.stringify({type:'join',room:id,role:'publisher',destination,voiceProfileId:voice}));const offer=await pcx.createOffer();await pcx.setLocalDescription(offer);ws.send(JSON.stringify({type:'offer',sdp:offer.sdp}))};ws.onmessage=async e=>{const m=JSON.parse(e.data);if(m.type==='answer')await pcx.setRemoteDescription({type:'answer',sdp:m.sdp});if(m.type==='candidate')await pcx.addIceCandidate(m.candidate)};ws.onerror=()=>addLog('Signaling gateway error','error');setCallState('active');addLog('Video call transport started','success')}catch(e){addLog(e.message||'Unable to start call','error')}};
 const startStream=async()=>{if(streamState==='live'){setStreamState('idle');addLog('Live stream stopped');return}if(!camera&&!screen&&!media)return addLog('Start the camera, share your screen, or load a video source','error');if(!voice)return addLog('Select an authorized voice profile','error');if(!env.whip)return addLog('VITE_LIVESIM_WHIP_URL is not configured; live publishing is not started','error');try{const s=streamRef.current;if(!s)return addLog('No media tracks available','error');const pcx=new RTCPeerConnection();pc.current=pcx;s.getTracks().forEach(t=>pcx.addTrack(t,s));const offer=await pcx.createOffer();await pcx.setLocalDescription(offer);const r=await fetch(env.whip,{method:'POST',headers:{'Content-Type':'application/sdp'},body:offer.sdp});if(!r.ok)throw new Error('Media gateway rejected the publish request');const answer=await r.text();await pcx.setRemoteDescription({type:'answer',sdp:answer});setStreamState('live');addLog('Live publish transport connected','success')}catch(e){addLog(e.message||'Live publish failed','error')}};
 const visual={filter:`brightness(${brightness}%) contrast(${contrast}%) saturate(${saturation}%)`,transform:`scaleX(${mirror?-1:1}) scale(${100/100})`};
 return <section className="liveEngine">
  <div className="engineHero"><div><span className="engineKicker">LIVESIM SESSION ENGINE / DEEPFACELIVE-STYLE PIPELINE</span><h2>Video call + live streaming control room</h2><p>Camera or file → face processing worker → authorized voice → transport → connected destination. Each transport is real only when its configured backend is online.</p></div><div className="engineHealth"><span className={worker==='online'?'good':''}/><b>{worker==='online'?'PROCESSOR ONLINE':'PROCESSOR '+worker.toUpperCase()}</b><small>Deep-Live worker</small></div></div>
  <div className="sceneStrip"><div className="sceneTitle"><span>SCENES</span><small>Recall studio configurations</small></div>{['call','stream','screen','media'].map(x=><button key={x} className={scene===x?'active':''} onClick={()=>{setScene(x);setMode(x==='stream'||x==='media'?'stream':'call')}}>{x==='call'?'Video Call':x==='stream'?'Live Stream':x==='screen'?'Screen Studio':'Media Playback'}</button>)}<button className="saveScene" onClick={saveScene}><Save size={14}/> Save</button></div>
  <div className="engineTabs"><button className={mode==='call'?'active':''} onClick={()=>setMode('call')}><Phone size={15}/> Video Call</button><button className={mode==='stream'?'active':''} onClick={()=>setMode('stream')}><Radio size={15}/> Live Stream</button><button className={mode==='pipeline'?'active':''} onClick={()=>setMode('pipeline')}><SlidersHorizontal size={15}/> Pipeline</button></div>
  <div className="engineGrid">
   <div className="engineStage"><div className="stageHead"><div><span>SOURCE / OUTPUT</span><b>{mode==='call'?'CALL PREVIEW':mode==='stream'?'LIVE PREVIEW':'PIPELINE PREVIEW'}</b></div><span className="liveBadge"><CircleDot size={11}/> {callState==='active'?'CALL LIVE':streamState==='live'?'STREAM LIVE':'READY'}</span></div><div className="engineVideo">{media&&!camera&&!screen?<video src={media.url} controls playsInline style={visual} onLoadedMetadata={e=>e.currentTarget.playbackRate=speed}/>:<video ref={cameraRef} autoPlay muted playsInline/>}<div className="videoHud"><span>{screen?'SCREEN / WINDOW':camera?'CAMERA':media?'FILE SOURCE':'NO SOURCE'}</span><span>{worker==='online'?'PROCESSING READY':'WORKER OFFLINE'}</span></div>{!camera&&!screen&&!media&&<div className="emptyVideo"><Video size={28}/><b>No video source</b><small>Camera, screen/window or video file</small></div>}</div><div className="stageActions"><button onClick={startCamera} className={camera?'on':''}>{camera?<CameraOff size={15}/>:<Camera size={15}/>} {camera?'Stop camera':'Start camera'}</button><button onClick={startScreen} className={screen?'on':''}>{screen?<X size={15}/>:<MonitorUp size={15}/>} {screen?'Stop share':'Screen / Window'}</button><button onClick={()=>fileRef.current?.click()}><Upload size={15}/> Load video</button><button onClick={startRecording} className={recording?'on':''}>{recording?<Square size={14}/>:<CircleDot size={14}/>} {recording?'Stop rec':'Record'}</button><input ref={fileRef} hidden type="file" accept="video/*" onChange={loadMedia}/><button onClick={startMic} className={mic?'on':''}>{mic?<MicOff size={15}/>:<Mic size={15}/>} {mic?'Mute mic':'Mic'}</button></div><div className="level"><span>MIC LEVEL</span><i><b style={{width:`${Math.max(2,level*100)}%`}}/></i></div></div>
   <aside className="engineSide"><div className="sideBlock"><span>DESTINATION</span><div className="platformGrid">{PLATFORMS.map(([id,name])=><button key={id} className={destination===id?'selected':''} onClick={()=>{setDestination(id);setConnected(false)}}>{name}</button>)}</div>{destination&&destination!=='webrtc'&&destination!=='rtmp'&&<button className="connect" onClick={connectPlatform}><Wifi size={14}/> {connected?'Connected':'Connect account'}</button>}{destination==='rtmp'&&<small className="sideNote">RTMP publishing requires a configured media gateway; browser code does not send RTMP directly.</small>}</div>
    <div className="sideBlock"><span>AUTHORIZED VOICE</span><div className="voiceLine"><Volume2 size={15}/><input value={voice} onChange={e=>setVoice(e.target.value)} placeholder="Voice profile ID"/></div><small className="sideNote">The session accepts only an existing authorized voice profile. No demo voice is substituted.</small></div>
    <div className="sideBlock"><span>VIDEO CONTROL</span>{[['Brightness',brightness,setBrightness,50,150],['Contrast',contrast,setContrast,50,150],['Saturation',saturation,setSaturation,0,180],['Speed',speed,setSpeed,.5,2]].map(([n,v,set,min,max])=><label className="engineRange" key={n}><b>{n}</b><span>{n==='Speed'?v.toFixed(2)+'×':v+'%'}</span><input type="range" min={min} max={max} step={n==='Speed'?.05:1} value={v} onChange={e=>set(Number(e.target.value))}/></label>)}<button onClick={()=>setMirror(!mirror)} className={mirror?'selected':''}>Mirror {mirror?'on':'off'}</button></div>
   </aside>
  </div>
  <div className="transportBar"><div><span>{mode==='call'?'CALL TRANSPORT':'STREAM TRANSPORT'}</span><b>{mode==='call'?callState.toUpperCase():streamState.toUpperCase()}</b></div><div className="transportInfo"><WifiOff size={14}/><span>Gateway: {gateway}</span><span>Worker: {worker}</span></div>{mode==='call'?<button className="primary" onClick={startCall}>{callState==='active'?<><Square size={14}/> End call</>:<><Phone size={14}/> Start video call</>}</button>:mode==='stream'?<button className="primary" onClick={startStream}>{streamState==='live'?<><Square size={14}/> Stop live</>:<><Radio size={14}/> Start live stream</>}</button>:<button className="primary" onClick={()=>addLog(worker==='online'?'Pipeline worker ready':'Connect the Deep-Live worker before running inference',worker==='online'?'success':'error')}><Zap size={14}/> Run pipeline check</button>}</div>
  <div className="pipeline"><div className="pipelineHead"><div><span>PROCESSING CONVEYOR</span><b>DeepFaceLive-inspired module chain</b></div><small>Source → detector → marker → model → merger → output</small></div><div className="pipelineNodes">{PIPELINE.map(([id,label],i)=><React.Fragment key={id}><div className={`node ${worker==='online'?'ready':''}`}><span>0{i+1}</span><b>{label}</b><small>{i===0?'Camera / file':i===1?'Detection':i===2?'Landmarks':i===3?'DFM / animator':i===4?'Composite':i===5?'WebRTC / gateway':'Module'}</small></div>{i<PIPELINE.length-1&&<i className="pipe"/>}</React.Fragment>)}</div></div>
  {savedScenes.length>0&&<div className="savedScenes"><span>SAVED SCENES</span>{savedScenes.map(s=><button key={s.id} onClick={()=>loadScene(s)}>{s.name}</button>)}</div>}<div className="engineLog"><div><span>SESSION LOG</span><b>Transport events</b></div>{log.length?log.map((x,i)=><div className={'logRow '+x.type} key={i}><code>{x.time}</code><span>{x.text}</span></div>):<div className="logEmpty">No session events yet.</div>}</div>
  <div className="engineFoot"><ShieldCheck size={15}/><span>Use only media, faces and accounts you are authorized to use. LiveSim does not mark an offline transport as connected and does not fabricate a call or stream.</span></div>
 </section>
}
