import React,{useEffect,useRef,useState} from 'react';
import {FaceDetector,FilesetResolver} from '@mediapipe/tasks-vision';
import {Camera,CameraOff,CircleDot,Mic,MicOff,MonitorUp,Phone,Radio,Save,ShieldCheck,SlidersHorizontal,Square,Upload,Video,Volume2,Wifi,WifiOff,X,Zap,Image as ImageIcon,Play,Pause,RefreshCw,ExternalLink} from 'lucide-react';

const PIPELINE=[['source','Camera / File Source'],['detect','Face Detector'],['mark','Face Marker'],['swap','Face Swapper / Animator'],['merge','Face Merger'],['output','Stream Output']];
const PLATFORMS=[['whatsapp','WhatsApp'],['google','Google Meet'],['zoom','Zoom'],['telegram','Telegram'],['tiktok','TikTok LIVE'],['rtmp','Custom RTMP'],['webrtc','WebRTC peer']];

function AvatarStudio({onReady}){
 const [target,setTarget]=useState(null),[driver,setDriver]=useState(false),[tracking,setTracking]=useState(false),[renderer,setRenderer]=useState('proxy'),[calibrated,setCalibrated]=useState(false),[status,setStatus]=useState('idle'),[fps,setFps]=useState(0),[face,setFace]=useState({x:0,y:0,scale:1,rotation:0,mouth:0}),[gpuSession,setGpuSession]=useState(null),[gpuState,setGpuState]=useState('offline'),[streamReady,setStreamReady]=useState(false);
 const cam=useRef(null),track=useRef(null),raf=useRef(null),last=useRef(performance.now()),frames=useRef(0),targetUrl=useRef(null),detector=useRef(null),outputCanvas=useRef(null),outputStream=useRef(null),targetImage=useRef(null),driverCanvas=useRef(null),gpuBusy=useRef(false);
 const worker=import.meta.env.VITE_DEEP_LIVE_WORKER_URL||'';const gpuWorker=import.meta.env.VITE_LIVESIM_GPU_WORKER_URL||worker;const gpuSocket=useRef(null);
 useEffect(()=>()=>{stopDriver();if(targetUrl.current)URL.revokeObjectURL(targetUrl.current)},[]);
 useEffect(()=>{if(!target||!outputCanvas.current)return;const canvas=outputCanvas.current;canvas.width=1280;canvas.height=720;if(!outputStream.current&&canvas.captureStream)outputStream.current=canvas.captureStream(30);setStreamReady(Boolean(outputStream.current))},[target]);
 useEffect(()=>{if(target&&outputStream.current&&streamReady)onReady?.({...target,stream:outputStream.current})},[target,streamReady]);
 useEffect(()=>{if(driver&&gpuSession&&renderer==='gpu'&&target&&gpuSocket.current?.readyState!==1)connectGpuDriver()},[driver,gpuSession,renderer,target]);
 const loadTarget=e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return setStatus('Choose a portrait image');if(targetUrl.current)URL.revokeObjectURL(targetUrl.current);targetUrl.current=URL.createObjectURL(f);const image=new Image();image.onload=()=>{targetImage.current=image};image.src=targetUrl.current;const v={name:f.name,url:targetUrl.current,file:f};setTarget(v);setStatus('target-ready');if(gpuSession)uploadTargetToGpu(gpuSession,f).catch(e=>setStatus(e.message));onReady?.({...v,stream:null});};
 const startDriver=async()=>{if(driver){stopDriver();return}try{await initDetector();const s=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:false});track.current=s;cam.current.srcObject=s;setDriver(true);setTracking(Boolean(detector.current));setStatus(detector.current?'tracking':'tracker-unavailable');if(detector.current){if(gpuSession)connectGpuDriver();loop()}}catch(e){setStatus(e?.name==='NotAllowedError'?'Camera permission denied':'Camera unavailable')}};
 const stopDriver=()=>{track.current?.getTracks().forEach(t=>t.stop());track.current=null;if(cam.current)cam.current.srcObject=null;detector.current?.close?.();detector.current=null;gpuSocket.current?.close?.();gpuSocket.current=null;setDriver(false);setTracking(false);if(raf.current)cancelAnimationFrame(raf.current);setFps(0)};
 const connectGpuDriver=()=>{if(!gpuSession||!gpuWorker||!target)return;const u=gpuWorker.replace(/^http/,'ws').replace(/\/$/,'')+'/sessions/'+gpuSession+'/driver';const ws=new WebSocket(u);ws.binaryType='blob';gpuSocket.current=ws;ws.onopen=()=>setGpuState('streaming');ws.onmessage=e=>{if(typeof e.data==='string')return;const url=URL.createObjectURL(e.data);const img=new Image();img.onload=()=>{const canvas=outputCanvas.current;if(canvas){const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,canvas.width,canvas.height)}URL.revokeObjectURL(url)};img.src=url};ws.onclose=()=>setGpuState('ready');ws.onerror=()=>setGpuState('error');};
 const initDetector=async()=>{try{const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm');detector.current=await FaceDetector.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite',delegate:'GPU'},runningMode:'VIDEO',minDetectionConfidence:.55});setStatus('tracking-ready')}catch(e){detector.current=null;setStatus('Face tracker unavailable') }};
 const loop=()=>{const now=performance.now();frames.current++;if(now-last.current>1000){setFps(frames.current);frames.current=0;last.current=now}const v=cam.current;if(v?.videoWidth&&detector.current&&v.readyState>=2){try{const result=detector.current.detectForVideo(v,now);const d=result.detections?.[0];if(d){const b=d.boundingBox,k=d.keypoints||[];const cx=b.originX+b.width/2,cy=b.originY+b.height/2;const nx=Math.max(-14,Math.min(14,(cx/v.videoWidth-.5)*34)),ny=Math.max(-10,Math.min(10,(cy/v.videoHeight-.5)*24));const scale=Math.max(.82,Math.min(1.18,1+((b.width/v.videoWidth)-.35)*.9));let rotation=0;if(k.length>=2){const a=k[0],bb=k[1];rotation=Math.max(-18,Math.min(18,Math.atan2(bb.y-a.y,bb.x-a.x)*180/Math.PI))}const next={x:nx,y:ny,scale,rotation,mouth:0};setFace(next);setTracking(true);drawOutput(next)}else setTracking(false)}catch{}}raf.current=requestAnimationFrame(loop)};
 const drawOutput=(f)=>{const canvas=outputCanvas.current,img=targetImage.current;if(!canvas||!img?.complete)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);const scale=Math.min(canvas.width/img.naturalWidth,canvas.height/img.naturalHeight)*.82;const w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.save();ctx.translate(canvas.width/2+f.x*12,canvas.height/2+f.y*8);ctx.rotate(f.rotation*Math.PI/180);ctx.scale(f.scale,f.scale);ctx.drawImage(img,-w/2,-h/2,w,h);ctx.restore();if(renderer==='gpu'&&gpuSocket.current?.readyState===1&&cam.current?.videoWidth&&!gpuBusy.current){const d=driverCanvas.current||(driverCanvas.current=document.createElement('canvas'));d.width=640;d.height=360;const dc=d.getContext('2d');dc.drawImage(cam.current,0,0,d.width,d.height);gpuBusy.current=true;d.toBlob(blob=>{if(blob&&gpuSocket.current?.readyState===1)gpuSocket.current.send(blob);gpuBusy.current=false},'image/jpeg',.78)}};
 const calibrate=()=>{if(!driver)return setStatus('Start the motion driver first');setCalibrated(true);setStatus('calibrated')};
 const uploadTargetToGpu=async(sessionId,targetFile)=>{if(!gpuWorker||!sessionId||!targetFile)return false;const fd=new FormData();fd.append('source',targetFile);const r=await fetch(gpuWorker.replace(/\/$/,'')+'/sessions/'+sessionId+'/source',{method:'POST',body:fd});if(!r.ok)throw new Error(await r.text());return true};
 const useGpu=async()=>{if(!gpuWorker)return setStatus('GPU worker URL is not configured');try{const r=await fetch(gpuWorker.replace(/\/$/,'')+'/sessions',{method:'POST'});if(!r.ok)throw new Error('GPU worker rejected the session');const data=await r.json();if(data.status!=='ready')throw new Error(data.error||'GPU renderer failed to initialize');setGpuSession(data.sessionId);setGpuState('ready');setRenderer('gpu');if(target?.file)await uploadTargetToGpu(data.sessionId,target.file);setStatus('gpu-ready')}catch(e){setGpuState('offline');setStatus(e.message||'GPU worker unavailable')}};
 return <section className="avatarStudio">
  <div className="avatarHeader"><div><span>AVATAR / FACE STUDIO</span><h3>Drive an uploaded face with your camera</h3><p>Your camera supplies motion. The selected portrait is the visible identity. The GPU renderer can replace the browser motion proxy when a configured worker is online.</p></div><div className="avatarStatus"><i className={tracking?'live':''}/>{tracking?'FACE DRIVER LIVE':'DRIVER IDLE'}<small>{renderer==='gpu'?'GPU renderer':'Browser motion proxy'}</small></div></div>
  <div className="avatarGrid">
   <div className="avatarPreview"><div className="avatarCanvas">{target?<canvas ref={outputCanvas} className="avatarOutputCanvas" aria-label="Neural avatar output"/>:<div className="avatarEmpty"><ImageIcon size={30}/><b>Upload a portrait</b><small>The portrait becomes the visible face.</small></div>}<div className="avatarHud"><span>{tracking?'DRIVER TRACKING':'READY'}</span><span>{fps?fps+' FPS':'-- FPS'}</span></div></div><video ref={cam} muted autoPlay playsInline className="driverPreview"/><div className="avatarActions"><button onClick={()=>document.getElementById('avatar-target-input')?.click()}><Upload size={15}/> Upload face</button><button className={driver?'on':''} onClick={startDriver}>{driver?<><CameraOff size={15}/> Stop driver</>:<><Camera size={15}/> Use my camera</>}</button><button onClick={calibrate} disabled={!driver}><RefreshCw size={15}/> Calibrate</button><input id="avatar-target-input" hidden type="file" accept="image/*" onChange={loadTarget}/></div></div>
   <aside className="avatarControls"><div><span>RENDER MODE</span><button className={renderer==='proxy'?'selected':''} onClick={()=>setRenderer('proxy')}>Face tracking preview</button><button className={renderer==='gpu'?'selected':''} onClick={useGpu}>GPU face renderer</button><small>MediaPipe tracks your camera locally. The GPU path is the production route for expression transfer, temporal stabilization and final rendered video.</small></div><div><span>DRIVER SIGNALS</span><label>Head position <b>{face.x.toFixed(1)}, {face.y.toFixed(1)}</b></label><label>Scale <b>{face.scale.toFixed(3)}×</b></label><label>Rotation <b>{face.rotation.toFixed(1)}°</b></label><label>Mouth activity <b>{Math.round(face.mouth*100)}%</b></label></div><div><span>SESSION HANDOFF</span><p>{target?'Target loaded: '+target.name:'No target image loaded.'}</p><button className="primary" disabled={!target||!driver} onClick={()=>onReady?.({...target,active:true,renderer,stream:outputStream.current})}><Play size={14}/> Use avatar in session</button></div></aside>
  </div>
 </section>
}

export default function LiveSessionEngine(){
 const [mode,setMode]=useState('call'),[camera,setCamera]=useState(false),[screen,setScreen]=useState(false),[mic,setMic]=useState(false),[media,setMedia]=useState(null),[voice,setVoice]=useState(''),[destination,setDestination]=useState(''),[connected,setConnected]=useState(false);
 const [callState,setCallState]=useState('idle'),[streamState,setStreamState]=useState('idle'),[worker,setWorker]=useState('checking'),[gateway,setGateway]=useState('checking');
 const [connection,setConnection]=useState(null),[connecting,setConnecting]=useState(false);
 const [brightness,setBrightness]=useState(100),[contrast,setContrast]=useState(100),[saturation,setSaturation]=useState(100),[speed,setSpeed]=useState(1),[mirror,setMirror]=useState(false),[level,setLevel]=useState(0),[log,setLog]=useState([]);
 const [room,setRoom]=useState(''),[scene,setScene]=useState('call'),[platformSession,setPlatformSession]=useState(null),[platformBusy,setPlatformBusy]=useState(false),[savedScenes,setSavedScenes]=useState([]),[recording,setRecording]=useState(false),[avatar,setAvatar]=useState(null),[showAvatar,setShowAvatar]=useState(true);
 const cameraRef=useRef(null),fileRef=useRef(null),streamRef=useRef(null),audioRef=useRef(null),raf=useRef(null),socket=useRef(null),pc=useRef(null),recorderRef=useRef(null),recordedRef=useRef([]);
 const env={worker:import.meta.env.VITE_DEEP_LIVE_WORKER_URL||'',signal:import.meta.env.VITE_LIVESIM_SIGNAL_URL||'',whip:import.meta.env.VITE_LIVESIM_WHIP_URL||'',gateway:import.meta.env.VITE_LIVESIM_MEDIA_GATEWAY_URL||''};
 const addLog=(text,type='info')=>setLog(x=>[{time:new Date().toLocaleTimeString([],{hour12:false}),text,type},...x].slice(0,10));
 useEffect(()=>{Promise.all([env.worker?fetch(env.worker.replace(/\/$/,'')+'/health').then(r=>r.ok):Promise.resolve(false),env.gateway?fetch(env.gateway.replace(/\/$/,'')+'/health').then(r=>r.ok):Promise.resolve(false),fetch('/api/connections').then(r=>r.ok?r.json():{connected:false}).catch(()=>({connected:false}))]).then(([w,g,c])=>{setWorker(w?'online':'offline');setGateway(g?'online':'offline');if(c?.connected){setConnection(c);setConnected(true)}}).catch(()=>{setWorker('offline');setGateway('offline')});const q=new URLSearchParams(window.location.search);const provider=q.get('connected');if(provider){fetch('/api/connections').then(r=>r.json()).then(c=>{if(c?.connected){setConnection(c);setConnected(true)};addLog((c?.label||provider)+' account connected','success')}).catch(()=>{});window.history.replaceState({},'',window.location.pathname+window.location.hash)}return()=>cleanup()},[]);
 const cleanup=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());if(raf.current)cancelAnimationFrame(raf.current);audioRef.current?.close?.().catch?.(()=>{});socket.current?.close?.();pc.current?.close?.()};
 const startCamera=async()=>{if(camera){streamRef.current?.getTracks().filter(t=>t.kind==='video').forEach(t=>t.stop());setCamera(false);addLog('Camera source stopped');return}try{const s=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:false});streamRef.current=s;cameraRef.current.srcObject=s;setCamera(true);addLog('Camera source connected','success')}catch(e){addLog(e?.name==='NotAllowedError'?'Camera permission denied':'Camera source unavailable','error')}};
 const startScreen=async()=>{if(screen){streamRef.current?.getTracks().filter(t=>t.kind==='video').forEach(t=>t.stop());setScreen(false);addLog('Screen capture stopped');return}try{const s=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:30}},audio:true});s.getVideoTracks()[0].onended=()=>{setScreen(false);addLog('Screen sharing ended')};streamRef.current=s;if(cameraRef.current)cameraRef.current.srcObject=s;setScreen(true);setCamera(false);addLog('Screen/window capture connected','success')}catch(e){addLog(e?.name==='NotAllowedError'?'Screen-share permission cancelled':'Screen capture unavailable','error')}};
 const startRecording=()=>{if(recording){recorderRef.current?.stop();setRecording(false);return}const s=streamRef.current;if(!s)return addLog('Start a source before recording','error');try{recordedRef.current=[];const r=new MediaRecorder(s);recorderRef.current=r;r.ondataavailable=e=>e.data.size&&recordedRef.current.push(e.data);r.onstop=()=>{const blob=new Blob(recordedRef.current,{type:r.mimeType||'video/webm'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='livesim-session.webm';a.click();addLog('Session recording saved locally','success')};r.start(1000);setRecording(true);addLog('Local session recording started','success')}catch(e){addLog('Browser recording unavailable','error')}};
 const saveScene=()=>{const snapshot={id:crypto.randomUUID(),name:scene,mode,brightness,contrast,saturation,speed,mirror,voice,destination,avatar:avatar?.name||null};setSavedScenes(x=>[snapshot,...x].slice(0,6));addLog('Scene saved locally','success')};
 const loadScene=s=>{setScene(s.name);setMode(s.mode);setBrightness(s.brightness);setContrast(s.contrast);setSaturation(s.saturation);setSpeed(s.speed);setMirror(s.mirror);setVoice(s.voice);setDestination(s.destination);addLog('Scene loaded: '+s.name,'success')};
 const startMic=async()=>{if(mic){streamRef.current?.getTracks().filter(t=>t.kind==='audio').forEach(t=>t.stop());setMic(false);setLevel(0);addLog('Microphone stopped');return}try{const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});if(!streamRef.current)streamRef.current=new MediaStream();s.getTracks().forEach(t=>streamRef.current.addTrack(t));const C=window.AudioContext||window.webkitAudioContext;if(C){const c=new C(),a=c.createAnalyser();a.fftSize=256;c.createMediaStreamSource(s).connect(a);audioRef.current=c;const d=new Uint8Array(a.frequencyBinCount);const draw=()=>{a.getByteFrequencyData(d);let sum=0;for(const n of d)sum+=n;setLevel(Math.min(1,(sum/d.length)/255*3));raf.current=requestAnimationFrame(draw)};draw()}setMic(true);addLog('Microphone connected','success')}catch(e){addLog(e?.name==='NotAllowedError'?'Microphone permission denied':'Microphone unavailable','error')}};
 const loadMedia=e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('video/'))return addLog('Choose a video file','error');setMedia({file:f,url:URL.createObjectURL(f)});addLog('File source loaded: '+f.name,'success')};
 const externalPlatformUrl=id=>({whatsapp:'https://web.whatsapp.com/',telegram:'https://web.telegram.org/'}[id]||null);
 const connectPlatform=()=>{if(!destination)return addLog('Choose a destination first','error');if(destination==='rtmp')return addLog('RTMP uses the configured media gateway; no fake login is shown');if(destination==='webrtc')return addLog('WebRTC peer uses the signaling gateway');const external=externalPlatformUrl(destination);if(external){window.open(external,'_blank','noopener,noreferrer');addLog('Opened '+(destination==='whatsapp'?'WhatsApp':'Telegram')+' in a new tab. These platforms use their own login/session rather than LiveSim OAuth.','success');return}setConnecting(true);window.location.assign('/api/oauth/start?provider='+encodeURIComponent(destination));};
 const selectPlatform=id=>{setDestination(id);setConnected(false);setConnection(null);if(id==='whatsapp'||id==='telegram'){const external=externalPlatformUrl(id);window.open(external,'_blank','noopener,noreferrer');addLog('Opened '+(id==='whatsapp'?'WhatsApp':'Telegram')+' for account/session access','success');}else if(id==='google'||id==='zoom'||id==='tiktok'){setConnecting(true);window.location.assign('/api/oauth/start?provider='+encodeURIComponent(id));}};

 const startPlatformSession=async()=>{if(!destination||destination==='rtmp'||destination==='webrtc')return addLog('Choose Google Meet, Zoom, TikTok or another supported destination first','error');if(!media&&!avatar&&!camera&&!screen)return addLog('Start a media source or avatar first','error');if(!voice)return addLog('Select an authorized voice profile','error');if(destination!=='whatsapp'&&destination!=='telegram'&&!connection)return addLog('Authorize the destination account first','error');setPlatformBusy(true);try{const r=await fetch('/api/session/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mediaName:avatar?.name||media?.name||'LiveSim media',voiceProfileId:voice,destination})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Platform session could not be started');setPlatformSession(data.platform);addLog(data.platform?.message||'Platform session created','success');const url=data.platform?.meetingUri||data.platform?.startUrl||data.platform?.joinUrl;if(url)window.open(url,'_blank','noopener,noreferrer');}catch(e){addLog(e.message||'Platform session failed','error')}finally{setPlatformBusy(false)}};\n const startCall=async()=>{if(callState==='active'){pc.current?.close();socket.current?.close();setCallState('idle');addLog('Call session ended');return}if(!camera&&!screen&&!media&&!avatar)return addLog('Start a source or activate an avatar','error');if(!voice)return addLog('Select an authorized voice profile','error');if(!connected&&destination&&destination!=='webrtc')return addLog('Connect the destination account first','error');if(!env.signal)return addLog('VITE_LIVESIM_SIGNAL_URL is not configured; call transport is not started','error');try{const s=streamRef.current||new MediaStream();const pcx=new RTCPeerConnection();pc.current=pcx;s.getTracks().forEach(t=>pcx.addTrack(t,s));pcx.onicecandidate=e=>{if(e.candidate)socket.current?.send(JSON.stringify({type:'candidate',candidate:e.candidate}))};const ws=new WebSocket(env.signal);socket.current=ws;ws.onopen=async()=>{const id=room||crypto.randomUUID().slice(0,8);setRoom(id);ws.send(JSON.stringify({type:'join',room:id,role:'publisher',destination,voiceProfileId:voice,avatar:avatar?.name||null}));const offer=await pcx.createOffer();await pcx.setLocalDescription(offer);ws.send(JSON.stringify({type:'offer',sdp:offer.sdp}))};ws.onmessage=async e=>{const m=JSON.parse(e.data);if(m.type==='answer')await pcx.setRemoteDescription({type:'answer',sdp:m.sdp});if(m.type==='candidate')await pcx.addIceCandidate(m.candidate)};ws.onerror=()=>addLog('Signaling gateway error','error');setCallState('active');addLog('Video call transport started','success')}catch(e){addLog(e.message||'Unable to start call','error')}};
 const startStream=async()=>{if(streamState==='live'){setStreamState('idle');addLog('Live stream stopped');return}if(!camera&&!screen&&!media&&!avatar)return addLog('Start a source or activate an avatar','error');if(!voice)return addLog('Select an authorized voice profile','error');if(!env.whip)return addLog('VITE_LIVESIM_WHIP_URL is not configured; live publishing is not started','error');try{const s=streamRef.current;if(!s)return addLog('No media tracks available','error');const pcx=new RTCPeerConnection();pc.current=pcx;s.getTracks().forEach(t=>pcx.addTrack(t,s));const offer=await pcx.createOffer();await pcx.setLocalDescription(offer);const r=await fetch(env.whip,{method:'POST',headers:{'Content-Type':'application/sdp'},body:offer.sdp});if(!r.ok)throw new Error('Media gateway rejected the publish request');const answer=await r.text();await pcx.setRemoteDescription({type:'answer',sdp:answer});setStreamState('live');addLog('Live publish transport connected','success')}catch(e){addLog(e.message||'Live publish failed','error')}};
 const visual={filter:`brightness(${brightness}%) contrast(${contrast}%) saturate(${saturation}%)`,transform:`scaleX(${mirror?-1:1})`};
 return <section className="liveEngine">
  <div className="engineHero"><div><span className="engineKicker">LIVESIM SESSION ENGINE / REAL-TIME AVATAR PIPELINE</span><h2>Video call + live streaming control room</h2><p>Camera, screen or media source → face driver → authorized voice → processed output → call or stream transport.</p></div><div className="engineHealth"><span className={worker==='online'?'good':''}/><b>{worker==='online'?'PROCESSOR ONLINE':'PROCESSOR '+worker.toUpperCase()}</b><small>GPU media worker</small></div></div>
  {showAvatar&&<AvatarStudio onReady={a=>{setAvatar(a);if(a?.stream)streamRef.current=a.stream;addLog('Avatar target ready: '+a.name,'success')}}/>}
  <div className="sceneStrip"><div className="sceneTitle"><span>SCENES</span><small>Recall studio configurations</small></div>{['call','stream','screen','media'].map(x=><button key={x} className={scene===x?'active':''} onClick={()=>{setScene(x);setMode(x==='stream'||x==='media'?'stream':'call')}}>{x==='call'?'Video Call':x==='stream'?'Live Stream':x==='screen'?'Screen Studio':'Media Playback'}</button>)}<button className="saveScene" onClick={saveScene}><Save size={14}/> Save</button></div>
  <div className="engineTabs"><button className={mode==='call'?'active':''} onClick={()=>setMode('call')}><Phone size={15}/> Video Call</button><button className={mode==='stream'?'active':''} onClick={()=>setMode('stream')}><Radio size={15}/> Live Stream</button><button className={mode==='pipeline'?'active':''} onClick={()=>setMode('pipeline')}><SlidersHorizontal size={15}/> Pipeline</button></div>
  <div className="engineGrid">
   <div className="engineStage"><div className="stageHead"><div><span>SOURCE / OUTPUT</span><b>{mode==='call'?'CALL PREVIEW':mode==='stream'?'LIVE PREVIEW':'PIPELINE PREVIEW'}</b></div><span className="liveBadge"><CircleDot size={11}/> {callState==='active'?'CALL LIVE':streamState==='live'?'STREAM LIVE':'READY'}</span></div><div className="engineVideo">{avatar?<div className="sessionAvatar"><img src={avatar.url} alt="Avatar output"/></div>:media&&!camera&&!screen?<video src={media.url} controls playsInline style={visual} onLoadedMetadata={e=>e.currentTarget.playbackRate=speed}/>:<video ref={cameraRef} autoPlay muted playsInline style={visual}/>}<div className="videoHud"><span>{avatar?'AVATAR OUTPUT':screen?'SCREEN / WINDOW':camera?'CAMERA':media?'FILE SOURCE':'NO SOURCE'}</span><span>{worker==='online'?'GPU READY':'WORKER OFFLINE'}</span></div>{!camera&&!screen&&!media&&!avatar&&<div className="emptyVideo"><Video size={28}/><b>No video source</b><small>Camera, screen/window or avatar</small></div>}</div><div className="stageActions"><button onClick={startCamera} className={camera?'on':''}>{camera?<CameraOff size={15}/>:<Camera size={15}/>} {camera?'Stop camera':'Start camera'}</button><button onClick={startScreen} className={screen?'on':''}>{screen?<X size={15}/>:<MonitorUp size={15}/>} {screen?'Stop share':'Screen / Window'}</button><button onClick={()=>fileRef.current?.click()}><Upload size={15}/> Load video</button><button onClick={startRecording} className={recording?'on':''}>{recording?<Square size={14}/>:<CircleDot size={14}/>} {recording?'Stop rec':'Record'}</button><input ref={fileRef} hidden type="file" accept="video/*" onChange={loadMedia}/><button onClick={startMic} className={mic?'on':''}>{mic?<MicOff size={15}/>:<Mic size={15}/>} {mic?'Mute mic':'Mic'}</button><button onClick={()=>setShowAvatar(v=>!v)}><ImageIcon size={15}/> {showAvatar?'Hide avatar studio':'Avatar studio'}</button></div><div className="level"><span>MIC LEVEL</span><i><b style={{width:`${Math.max(2,level*100)}%`}}/></i></div></div>
   <aside className="engineSide"><div className="sideBlock"><span>DESTINATION</span><div className="platformGrid">{PLATFORMS.map(([id,name])=><button key={id} className={destination===id?'selected':''} onClick={()=>selectPlatform(id)} title={id==='rtmp'||id==='webrtc'?'Configure transport':'Open '+name+' connection'}>{name}{['whatsapp','telegram','google','zoom','tiktok'].includes(id)&&<ExternalLink size={11}/>}</button>)}</div>{destination&&destination!=='webrtc'&&destination!=='rtmp'&&<button className="connect" onClick={connectPlatform} disabled={connecting}><Wifi size={14}/> {connecting?'Opening…':connection?.provider===destination?'Connected — '+(connection.displayName||connection.label):'Open / connect account'}</button>}{destination&&['google','zoom','tiktok'].includes(destination)&&<button className="primary" onClick={startPlatformSession} disabled={platformBusy||(!connection)}><Play size={14}/> {platformBusy?'Starting…':destination==='tiktok'?'Verify creator / publish':'Create & open session'}</button>}{destination==='rtmp'&&<small className="sideNote">RTMP publishing requires a configured media gateway; browser code does not send RTMP directly.</small>}</div>
    <div className="sideBlock"><span>AUTHORIZED VOICE</span><div className="voiceLine"><Volume2 size={15}/><input value={voice} onChange={e=>setVoice(e.target.value)} placeholder="Voice profile ID"/></div><small className="sideNote">Use your own voice or a voice you have authorization to use.</small></div>
    <div className="sideBlock"><span>VIDEO CONTROL</span>{[['Brightness',brightness,setBrightness,50,150],['Contrast',contrast,setContrast,50,150],['Saturation',saturation,setSaturation,0,180],['Speed',speed,setSpeed,.5,2]].map(([n,v,set,min,max])=><label className="engineRange" key={n}><b>{n}</b><span>{n==='Speed'?v.toFixed(2)+'×':v+'%'}</span><input type="range" min={min} max={max} step={n==='Speed'?.05:1} value={v} onChange={e=>set(Number(e.target.value))}/></label>)}<button onClick={()=>setMirror(!mirror)} className={mirror?'selected':''}>Mirror {mirror?'on':'off'}</button></div>
   </aside>
  </div>
  <div className="transportBar"><div><span>{mode==='call'?'CALL TRANSPORT':'STREAM TRANSPORT'}</span><b>{mode==='call'?callState.toUpperCase():streamState.toUpperCase()}</b></div><div className="transportInfo"><WifiOff size={14}/><span>Gateway: {gateway}</span><span>Worker: {worker}</span></div>{mode==='call'?<button className="primary" onClick={startCall}>{callState==='active'?<><Square size={14}/> End call</>:<><Phone size={14}/> Start video call</>}</button>:mode==='stream'?<button className="primary" onClick={startStream}>{streamState==='live'?<><Square size={14}/> Stop live</>:<><Radio size={14}/> Start live stream</>}</button>:<button className="primary" onClick={()=>addLog(worker==='online'?'Pipeline worker ready':'Connect the GPU worker before running inference',worker==='online'?'success':'error')}><Zap size={14}/> Run pipeline check</button>}</div>
  <div className="pipeline"><div className="pipelineHead"><div><span>PROCESSING CONVEYOR</span><b>Real-time face-driven output architecture</b></div><small>Camera → tracking → renderer → compositor → output</small></div><div className="pipelineNodes">{PIPELINE.map(([id,label],i)=><React.Fragment key={id}><div className={`node ${worker==='online'?'ready':''}`}><span>0{i+1}</span><b>{label}</b><small>{i===0?'Camera / file':i===1?'Detection':i===2?'Landmarks':i===3?'Face renderer':i===4?'Composite':i===5?'WebRTC / gateway':'Module'}</small></div>{i<PIPELINE.length-1&&<i className="pipe"/>}</React.Fragment>)}</div></div>
  {savedScenes.length>0&&<div className="savedScenes"><span>SAVED SCENES</span>{savedScenes.map(s=><button key={s.id} onClick={()=>loadScene(s)}>{s.name}</button>)}</div>}<div className="engineLog"><div><span>SESSION LOG</span><b>Transport events</b></div>{log.length?log.map((x,i)=><div className={'logRow '+x.type} key={i}><code>{x.time}</code><span>{x.text}</span></div>):<div className="logEmpty">No session events yet.</div>}</div>
  <div className="engineFoot"><ShieldCheck size={15}/><span>Use only media, faces and accounts you are authorized to use. The MediaPipe tracking runs locally in the browser; the uploaded portrait is not claimed to be a neural face render until the GPU renderer is online.</span></div>
 </section>
}
