import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,ArrowUpRight,Check,ChevronDown,CircleDot,Command,Film,Headphones,Mic,MicOff,Play,Radio,RotateCcw,ShieldCheck,SlidersHorizontal,Square,Video,Volume2,X,Zap} from 'lucide-react';
import './styles.css';

const PLATFORMS=[
 {id:'whatsapp',name:'WhatsApp',kind:'Account connection',note:'Official account authorization required. Calling capabilities depend on the products and permissions available to the account.'},
 {id:'google',name:'Google Meet',kind:'Account connection',note:'Connect a Google account to work with supported Meet workflows.'},
 {id:'zoom',name:'Zoom',kind:'Account connection',note:'Connect an authorized Zoom account for supported meeting or SDK workflows.'},
 {id:'telegram',name:'Telegram',kind:'Account connection',note:'Connect a supported bot/account workflow. Arbitrary user-to-user calling is not assumed.'},
 {id:'tiktok',name:'TikTok LIVE',kind:'Account connection',note:'Creator/LIVE access depends on TikTok eligibility and approved capabilities.'},
 {id:'custom',name:'Custom RTMP / WebRTC',kind:'Endpoint',note:'Use a compatible destination endpoint without pretending it is an OAuth account.'}
];

function App(){
 const [boot,setBoot]=useState(true),[section,setSection]=useState('session'),[media,setMedia]=useState(null),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[brightness,setBrightness]=useState(100),[contrast,setContrast]=useState(100),[saturation,setSaturation]=useState(100),[zoom,setZoom]=useState(100),[mirror,setMirror]=useState(false),[mic,setMic]=useState(false),[micLevel,setMicLevel]=useState(0),[micError,setMicError]=useState(''),[destination,setDestination]=useState(''),[connected,setConnected]=useState(false),[account,setAccount]=useState(null),[events,setEvents]=useState([]),[session,setSession]=useState(false),[sessionData,setSessionData]=useState(null),[voice,setVoice]=useState(''),[voiceText,setVoiceText]=useState('');
 const fileRef=useRef(null),streamRef=useRef(null),audioCtx=useRef(null),analyser=useRef(null),frame=useRef(null),videoRef=useRef(null);
 useEffect(()=>{const t=setTimeout(()=>setBoot(false),1800);return()=>clearTimeout(t)},[]);
 useEffect(()=>{fetch('/api/connections').then(r=>r.ok?r.json():null).then(data=>{if(data?.connected){setConnected(true);setAccount(data);if(!destination)setDestination(data.provider);event('CONNECT',`Connected ${data.label} account: ${data.displayName}`,'success')}}).catch(()=>{});fetch('/api/session/status').then(r=>r.ok?r.json():null).then(data=>{if(data?.active){setSession(true);setSessionData(data);event('SESSION',`Restored simulation session ${data.id}`,'success')}}).catch(()=>{});},[]);

 const event=(type,text,level='info')=>setEvents(e=>[{time:new Date().toLocaleTimeString([],{hour12:false}),type,text,level},...e].slice(0,12));
 const loadVideo=e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('video/'))return event('MEDIA','Only video files are accepted','warning');if(media)URL.revokeObjectURL(media.url);const url=URL.createObjectURL(f);setMedia({url,name:f.name});event('MEDIA','Loaded user-supplied media: '+f.name,'success')};
 const toggleMic=async()=>{if(mic){streamRef.current?.getTracks().forEach(t=>t.stop());if(frame.current)cancelAnimationFrame(frame.current);if(audioCtx.current)await audioCtx.current.close().catch(()=>{});setMic(false);setMicLevel(0);event('MIC','Microphone stopped');return}
  setMicError('');try{const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});streamRef.current=s;const C=window.AudioContext||window.webkitAudioContext;if(C){const c=new C(),a=c.createAnalyser();a.fftSize=256;a.smoothingTimeConstant=.75;c.createMediaStreamSource(s).connect(a);audioCtx.current=c;analyser.current=a;const d=new Uint8Array(a.frequencyBinCount);const draw=()=>{a.getByteFrequencyData(d);let sum=0;for(const n of d)sum+=n;setMicLevel(Math.min(1,(sum/d.length)/255*3));frame.current=requestAnimationFrame(draw)};draw()}setMic(true);event('MIC','Microphone permission granted; input meter active','success')}catch(err){setMicError(err?.name==='NotAllowedError'?'Microphone permission was denied.':'Microphone could not be started.');event('MIC','Microphone access was not enabled','warning')}};
 useEffect(()=>()=>{streamRef.current?.getTracks().forEach(t=>t.stop());if(frame.current)cancelAnimationFrame(frame.current);if(media)URL.revokeObjectURL(media.url)},[media]);
 const visual={filter:`brightness(${brightness}%) contrast(${contrast}%) saturate(${saturation}%)`,transform:`scaleX(${mirror?-1:1}) scale(${zoom/100})`};
 const nav=id=>{setSection(id);document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})};
 const choose=p=>{setDestination(p);if(account?.provider!==p)setConnected(false);event('CONNECT','Selected '+PLATFORMS.find(x=>x.id===p)?.name)};
 const connect=()=>{if(!destination)return event('CONNECT','Select a destination first','warning');if(destination==='custom')return event('CONNECT','Custom destination uses endpoint configuration, not OAuth','info');if(!['google','zoom','tiktok'].includes(destination))return event('CONNECT','This provider needs its dedicated approved adapter; no fake OAuth flow is used.','warning');window.location.href=`/api/oauth/start?provider=${destination}`};
 const start=async()=>{if(session){await fetch('/api/session/stop',{method:'POST'});setSession(false);setSessionData(null);event('SESSION','Simulation session stopped','success');return}if(!media)return event('SESSION','Load a video before starting','warning');if(!voice)return event('SESSION','Select an authorized voice profile before starting','warning');if(!destination)return event('SESSION','Choose a destination before starting','warning');if(!connected||!account)return event('SESSION','Authorize the selected destination before starting','warning');try{const response=await fetch('/api/session/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mediaName:media.name,voiceProfileId:voice,destination})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Session could not start.');setSession(true);setSessionData(data);event('SESSION',`Simulation session ${data.id} ready: media → voice → ${data.destination}`,'success')}catch(error){event('SESSION',error.message,'warning')}};
 return <div className="shell">
  {boot&&<div className="curtain"><div className="counter">00<span>%</span></div><div className="bootline"><span>LIVE SIM LAB</span><span>INITIALIZING RESEARCH CONSOLE</span></div><div className="progress"><i/></div></div>}
  <header className="top"><div className="brand"><div className="mark">LS</div><div><b>LiveSim Lab</b><small>MEDIA SIMULATION CONSOLE</small></div></div><div className="safety"><span/> SIMULATION MODE <i/> NO REAL IDENTITIES</div><button className="iconBtn" onClick={()=>event('SYSTEM','Audit marker added')}><Command size={15}/> Audit marker</button></header>
  <main>
   <section className="hero" id="session"><div className="heroCopy"><p className="kicker">SAFE MEDIA RESEARCH / 01</p><h1>Study the mechanics of a <em>convincing call.</em></h1><p>A controlled workspace for video, voice, playback cues and platform workflows — with the simulation boundary visible at every step.</p></div><div className="heroCard"><span>SESSION INPUT</span><input placeholder="Name this research session"/><small>Nothing is pre-populated, automatically authorized or presented as a real transaction.</small></div></section>
   <nav className="nav">{[['session','01 Session'],['media','02 Media'],['voice','03 Voice'],['destination','04 Connect'],['review','05 Review']].map(([id,label])=><button className={section===id?'on':''} onClick={()=>nav(id)} key={id}>{label}</button>)}</nav>
   <section className="workspace" id="media"><div className="stagePanel"><div className="panelTop"><div><p className="kicker">MEDIA STUDIO</p><h2>Call / stream preview</h2></div><span className="pill">SIMULATED MEDIA</span></div><div className="stage"><div className="grid"/>{media?<video ref={videoRef} src={media.url} controls playsInline style={visual} onLoadedMetadata={e=>e.currentTarget.playbackRate=speed}/>:<button className="dropzone" onClick={()=>fileRef.current?.click()}><Film size={28}/><b>Load video media</b><small>Choose a file from your device</small></button>}<div className="watermark">SIMULATED</div><div className="stageStatus"><span><CircleDot size={12}/> {session?'SIMULATION ACTIVE':'SESSION IDLE'}</span><span>{media?.name||'No media loaded'}</span></div></div><div className="transport"><button className="round" onClick={()=>{if(videoRef.current){videoRef.current.paused?videoRef.current.play():videoRef.current.pause();setPlaying(!videoRef.current.paused)}}}>{playing?<Square size={13}/>:<Play size={13}/>}</button><div className="track"><i style={{width:playing?'62%':'18%'}}/></div><span className="mono">{playing?'PLAYING':'READY'}</span><button className={session?'stop':'start'} onClick={start}>{session?'END SIMULATION':'START SIMULATION'}</button></div></div>
    <aside className="sidePanel"><div className="panelTop"><div><p className="kicker">SESSION GATE</p><h2>Readiness</h2></div><Activity size={18}/></div>{[['MEDIA',!!media],['VOICE',!!voice],['DESTINATION',!!destination],['AUTHORIZATION',connected]].map(([x,ok])=><div className="check" key={x}><span className={ok?'ok':''}>{ok?<Check size={13}/>:''}</span><b>{x}</b><small>{ok?'READY':'NOT READY'}</small></div>)}<div className="integrity"><ShieldCheck size={18}/><div><b>Integrity lock</b><small>No camera, wallet, credential or identity capture.</small></div></div>{sessionData&&<div className="sessionCard"><b>{sessionData.id}</b><small>SIMULATION · {sessionData.status.toUpperCase()}</small><span>Media → Authorized voice → {sessionData.destination} account</span></div>}</aside></section>
   <section className="studioGrid"><div className="panel controls" id="mediaControls"><div className="panelTop"><div><p className="kicker">EDIT</p><h2>Video controls</h2></div><SlidersHorizontal size={18}/></div>{[['Brightness',brightness,setBrightness,50,150],['Contrast',contrast,setContrast,50,150],['Saturation',saturation,setSaturation,0,180],['Zoom',zoom,setZoom,75,140],['Speed',speed,setSpeed,.5,2]].map(([n,v,set,min,max])=><label className="range" key={n}><span>{n}<b>{n==='Speed'?Number(v).toFixed(2)+'×':v+'%'}</b></span><input type="range" min={min} max={max} step={n==='Speed'?.05:1} value={v} onChange={e=>set(Number(e.target.value))}/></label>)}<div className="row"><button className={mirror?'accent':''} onClick={()=>setMirror(!mirror)}>Mirror {mirror?'on':'off'}</button><button onClick={()=>{setBrightness(100);setContrast(100);setSaturation(100);setZoom(100);setSpeed(1);setMirror(false)}}><RotateCcw size={14}/> Reset</button></div><p className="note">These are local, non-destructive presentation controls. A prerecorded person does not move because the viewer moves.</p></div>
    <div className="panel mic" id="voice"><div className="panelTop"><div><p className="kicker">VOICE INPUT</p><h2>Microphone</h2></div><Mic size={18}/></div><div className="orb" style={{'--level':micLevel}}><div/><i/><i/><i/></div><div className="micTitle"><b>{mic?'Microphone active':'Microphone ready'}</b><small>{mic?'Input level is being measured locally.':'Permission is requested only after you press the button.'}</small></div><div className="meter"><i style={{transform:`scaleX(${Math.max(.02,micLevel)})`}}/></div><button className={mic?'danger':'accentBtn'} onClick={toggleMic}>{mic?<><MicOff size={15}/> Turn mic off</>:<><Mic size={15}/> Allow microphone</>}</button>{micError&&<p className="error">{micError}</p>}<div className="voiceSelect"><label>Authorized voice profile</label><select value={voice} onChange={e=>{setVoice(e.target.value);event('VOICE','Voice profile selected')}}><option value="">Select saved voice</option><option value="authorized-profile">Authorized voice profile</option></select><small>Cloned voices remain restricted to voices the user owns or is authorized to use.</small></div><textarea value={voiceText} onChange={e=>setVoiceText(e.target.value)} placeholder="Speech text for an authorized synthetic voice…"/><button className="outline" disabled={!voiceText.trim()} onClick={()=>event('VOICE','Speech generation requested; provider adapter required')}>Generate synthetic speech <ArrowUpRight size={14}/></button></div>
    <div className="panel destination" id="destination"><div className="panelTop"><div><p className="kicker">CONNECTION CENTER</p><h2>Connect a destination</h2></div><Radio size={18}/></div><div className="platforms">{PLATFORMS.map(p=><button className={destination===p.id?'selected':''} onClick={()=>choose(p.id)} key={p.id}><span>{p.name}</span><small>{p.kind}</small><ChevronDown size={13}/></button>)}</div>{destination&&<div className="connectDetail"><b>{PLATFORMS.find(p=>p.id===destination)?.name}</b><p>{PLATFORMS.find(p=>p.id===destination)?.note}</p>{destination==='custom'?<input placeholder="RTMP / WebRTC endpoint"/>:<button className="accentBtn" disabled={!['google','zoom','tiktok'].includes(destination)} onClick={connect}><ShieldCheck size={15}/> {connected?'Account connected':(['google','zoom','tiktok'].includes(destination)?'Login & connect account':'Dedicated adapter required')}</button>}{connected&&account&&<div className="accountCard"><div className="accountAvatar">{account.avatarUrl?<img src={account.avatarUrl} alt="" />:<CircleDot size={15}/>}</div><div><b>{account.displayName}</b><small>{account.label} · authorized</small></div><button className="tiny" onClick={async()=>{await fetch('/api/disconnect');setConnected(false);setAccount(null);event('CONNECT','Account disconnected')}}>Disconnect</button></div>}<div className="connectionState">{connected?<><Check size={14}/> Account authorized</>:<>Authorization required before session start</>}</div>{destination==='google'&&<div className="connectionHint">Google account authorization is connected here; Meet-specific actions may require additional Google API scopes and approval.</div>}{destination==='tiktok'&&<div className="connectionHint">TikTok Login Kit authorizes the account; LIVE/content capabilities still depend on TikTok product access and approved scopes.</div>}</div>}</div>
   </section>
   <section className="reviewGrid" id="review"><div className="panel"><div className="panelTop"><div><p className="kicker">AUDIT LOG</p><h2>Timeline</h2></div><button className="tiny" onClick={()=>setEvents([])}>Clear</button></div>{events.length?events.map((e,i)=><div className="event" key={i}><time>{e.time}</time><span className={e.level}/><div><b>{e.type}</b><p>{e.text}</p></div></div>):<div className="empty">No events yet. Every meaningful control action appears here.</div>}</div><div className="panel research"><p className="kicker">RESEARCH BOUNDARY</p><h2>Designed for transparent experiments.</h2><p>LiveSim Lab can demonstrate how media, voice, playback and destination workflows feel without presenting synthetic content as a genuine live identity or transaction.</p><div className="boundary"><span><Check size={14}/> Synthetic media labels</span><span><Check size={14}/> User-supplied inputs</span><span><Check size={14}/> Server-side credentials</span><span><Check size={14}/> No real wallet signing</span></div></div></section>
  </main>
  <footer><span>LiveSim Lab / research console</span><span>SYNTHETIC MEDIA · AUTHORIZED VOICE · NO REAL TRANSACTIONS</span></footer>
  <input ref={fileRef} hidden type="file" accept="video/*" onChange={loadVideo}/>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);