import React,{useEffect,useRef,useState} from 'react';
import {Mic,Upload,Volume2,ShieldCheck,Play,Square,RefreshCw,Radio,MessageSquare,StopCircle} from 'lucide-react';

export default function VoiceBridge(){
 const worker=import.meta.env.VITE_LIVESIM_VOICE_WORKER_URL||'';
 const [status,setStatus]=useState('offline'),[profile,setProfile]=useState(null),[authorized,setAuthorized]=useState(false),[transcript,setTranscript]=useState(''),[text,setText]=useState(''),[audioUrl,setAudioUrl]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [live,setLive]=useState(false),[liveText,setLiveText]=useState(''),[liveLatency,setLiveLatency]=useState(null),[recognitionAvailable,setRecognitionAvailable]=useState(false);
 const audio=useRef(null),bridgeAudio=useRef(null),recognition=useRef(null),liveRef=useRef(false),lastLiveAt=useRef(0);
 useEffect(()=>{if(!worker)return;fetch(worker.replace(/\/$/,'')+'/health').then(r=>r.ok?r.json():null).then(d=>setStatus(d?.ok?'online':'error')).catch(()=>setStatus('offline'));const base=import.meta.env.VITE_LIVESIM_MEDIA_BRIDGE_URL||'ws://127.0.0.1:8788/ws/publish';const audioUrl=base.replace('/ws/publish','/ws/audio/publish');try{bridgeAudio.current=new WebSocket(audioUrl);bridgeAudio.current.onerror=()=>{}}catch{}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;setRecognitionAvailable(Boolean(SR));return()=>{liveRef.current=false;recognition.current?.stop?.();bridgeAudio.current?.close?.()},[worker]);
 const upload=async e=>{const f=e.target.files?.[0];if(!f)return;if(!authorized)return setMessage('Confirm that you own or have permission to use this voice.');if(!transcript.trim())return setMessage('Add the exact transcript spoken in the reference sample.');if(!worker)return setMessage('Voice worker URL is not configured.');setBusy(true);setMessage('Loading voice profile…');try{const fd=new FormData();fd.append('audio',f);fd.append('transcript',transcript);fd.append('authorized','true');const r=await fetch(worker.replace(/\/$/,'')+'/profiles',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail||d.error||'Profile creation failed');setProfile({id:d.id,name:f.name});localStorage.setItem('livesim.voiceProfileId',d.id);setMessage('Voice profile ready and selected for the session engine.');}catch(err){setMessage(err.message)}finally{setBusy(false)}};
 const sendWav=async blob=>{if(bridgeAudio.current?.readyState===1)bridgeAudio.current.send(await blob.arrayBuffer())};
 const synthText=async value=>{if(!profile||!value.trim()||!worker)return false;const started=performance.now();const r=await fetch(worker.replace(/\/$/,'')+'/synthesize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId:profile.id,text:value.trim(),steps:12,speed:1})});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.detail||'Synthesis failed')}const blob=await r.blob();await sendWav(blob);setLiveLatency(Math.round(performance.now()-started));return blob};
 const synth=async()=>{if(!profile)return setMessage('Create a voice profile first.');if(!text.trim())return setMessage('Enter text to synthesize.');setBusy(true);setMessage('Generating speech…');try{const blob=await synthText(text);if(audioUrl)URL.revokeObjectURL(audioUrl);const u=URL.createObjectURL(blob);setAudioUrl(u);setMessage('Speech generated and sent to the local OBS audio source.');setTimeout(()=>audio.current?.play().catch(()=>{}),0)}catch(err){setMessage(err.message)}finally{setBusy(false)}};
 const startLive=()=>{if(!profile)return setMessage('Create the authorized voice profile first.');if(!recognitionAvailable)return setMessage('This browser does not expose SpeechRecognition. Use the GPU/RVC live-conversion worker path instead.');if(liveRef.current)return stopLive();const SR=window.SpeechRecognition||window.webkitSpeechRecognition;const r=new SR();r.continuous=true;r.interimResults=true;r.lang=navigator.language||'en-US';r.maxAlternatives=1;r.onstart=()=>{liveRef.current=true;setLive(true);setMessage('Live clone conversation is listening. Speak normally.');};r.onresult=async event=>{let finalText='';let interim='';for(let i=event.resultIndex;i<event.results.length;i++){const t=event.results[i][0]?.transcript||'';if(event.results[i].isFinal)finalText+=t+' ';else interim+=t}setLiveText((finalText||interim).trim());if(finalText.trim()&&Date.now()-lastLiveAt.current>250){lastLiveAt.current=Date.now();try{await synthText(finalText.trim())}catch(err){setMessage(err.message)}}};r.onerror=e=>setMessage('Live recognition: '+(e.error||'error'));r.onend=()=>{if(liveRef.current){try{r.start()}catch{}}else setLive(false)};recognition.current=r;try{r.start()}catch(e){setMessage(e.message)}};
 const stopLive=()=>{liveRef.current=false;recognition.current?.stop?.();recognition.current=null;setLive(false);setLiveText('');setMessage('Live clone conversation stopped.')};
 const stop=()=>{audio.current?.pause();if(audio.current)audio.current.currentTime=0};
 return <section className='voiceBridge'><div className='voiceHero'><div><span>AUTHORIZED VOICE ENGINE</span><h2>Voice clone → live conversation</h2><p>Upload a reference sample you own or have permission to use. The same profile can drive generated speech and the live speech-to-cloned-voice bridge.</p></div><div className={'voiceState '+status}><i/>{status.toUpperCase()}</div></div>
 <div className='voiceGrid'><div className='voiceCard'><div className='voiceHead'><ShieldCheck size={20}/><div><b>1. Create voice profile</b><small>Reference audio + exact transcript</small></div></div>
 <label className='voiceConsent'><input type='checkbox' checked={authorized} onChange={e=>setAuthorized(e.target.checked)}/> I own this voice or have explicit permission to clone it.</label>
 <textarea value={transcript} onChange={e=>setTranscript(e.target.value)} placeholder='Exact words spoken in the reference recording…' rows='3'/>
 <input id='voice-ref' hidden type='file' accept='audio/*' onChange={upload}/><button onClick={()=>document.getElementById('voice-ref')?.click()} disabled={busy||!authorized}><Upload size={15}/> {profile?'Replace reference':'Load reference audio'}</button>
 {profile&&<div className='voiceProfile'><Mic size={15}/><b>{profile.name}</b><span>{profile.id}</span></div>}</div>
 <div className='voiceCard'><div className='voiceHead'><Volume2 size={20}/><div><b>2. Generate speech</b><small>F5-TTS reference-voice synthesis</small></div></div>
 <textarea value={text} onChange={e=>setText(e.target.value)} placeholder='Type what the authorized voice should say…' rows='5'/>
 <button className='primary' onClick={synth} disabled={busy||!profile}>{busy?<><RefreshCw size={15}/> Working…</>:<><Play size={15}/> Generate voice</>}</button>
 {audioUrl&&<div className='voicePlayer'><audio ref={audio} src={audioUrl} controls/><button onClick={stop}><Square size={13}/> Stop</button></div>}</div></div>
 <div className='liveVoiceCard'><div><span>LIVE CLONE CONVERSATION</span><h3>Speak normally → LiveSim speaks back in the cloned voice</h3><p>This browser mode turns finalized speech-recognition chunks into short F5-TTS responses and routes the resulting audio to the local media bridge. For lower-latency direct microphone conversion, the project now exposes a separate RVC/ONNX worker integration point.</p></div><div className='liveVoiceControls'><button className={live?'dangerLive':'primary'} onClick={live?stopLive:startLive} disabled={!profile||status!=='online'}>{live?<><StopCircle size={16}/> Stop live voice</>:<><Radio size={16}/> Start live voice</>}</button><span className={'liveIndicator '+(live?'on':'')}>{live?'LISTENING':'STANDBY'}</span></div>{liveText&&<div className='liveTranscript'><MessageSquare size={15}/><span>{liveText}</span></div>}{liveLatency!=null&&<small className='liveLatency'>Last clone chunk: {liveLatency} ms worker round-trip</small>}</div>
 <div className='voiceNotice'>{message||'Voice output is local to the configured worker. No voice sample is uploaded to Vercel.'}</div>
 </section>
}
